export const references=[
 {id:'electric-motor',style:'simulation',title:'电车电机怎样转起来',topic:'以特斯拉电车为引子，交互讲解永磁同步电机的通用原理，调节磁场转速、反转和查看定子转子',summary:'调节旋转磁场，观察转子与磁场的同步关系。',accent:'#ffb369',bg:'#141c26',ink:'#edf4fb',controls:[['speed','磁场转速（示意）',0,100,38],['direction','旋转方向',-1,1,1]],note:'这是永磁同步电机的通用教学模型，不是特定车型拆解或性能测量；不同车型的电机类型可能不同。',source:'https://www.tesla.com/ownersmanual/model3/en_gb/GUID-E414862C-CFA1-4A0B-9548-BE21C32CAA58.html'},
 {id:'human-layers',style:'anatomy',title:'人体 3D 透视实验室',topic:'人体3D透视图：拖动旋转、切换皮肤骨骼器官层，选择心脏、肺、肝和胃查看概念性说明',summary:'拖动三维人体，切换结构层并查看器官。',accent:'#79dcd5',bg:'#101f2c',ink:'#e3f4f7',controls:[['opacity','外层透明度',0,100,18],['rotation','观察角度',-180,180,0]],note:'结构位置与比例经过简化，供一般科学学习使用。',buttons:[['organs','器官'],['skeleton','骨骼'],['skin','外形']]},
 {id:'ink-water',style:'ink',title:'山水间的一滴水',topic:'用水墨山水体验水循环，调节日照与降水，观察蒸发、凝结和回流',summary:'调节日照和降水，追踪一滴水的循环。',accent:'#526b5c',bg:'#f5f1e7',ink:'#303831',controls:[['sun','日照强度',0,100,55],['rain','降水强度',0,100,35]],note:'水在蒸发、凝结、降水与回流之间循环；粒子速度是示意。'},
 {id:'leaf-lab',style:'watercolor',title:'叶子的光合作用工坊',topic:'水彩植物实验，改变光照与二氧化碳供应，观察光合作用的限制因素和氧气反馈',summary:'改变光照与气体供应，发现限制因素。',accent:'#59856a',bg:'#f1f4e7',ink:'#304c3c',controls:[['light','光照（相对强度）',0,100,65],['co2','二氧化碳供应（相对量）',0,100,55]],note:'采用两项限制因素的简化模型，反馈为相对值，不是实际产量预测。'},
 {id:'circuit-lab',style:'blueprint',title:'电路参数实验台',topic:'工程蓝图风格直流电路，调节电压、电阻和开关，按欧姆定律计算电流与功率',summary:'连接开关，观察电流、电压与电阻的关系。',accent:'#82ddff',bg:'#102d4c',ink:'#e9f7ff',controls:[['voltage','电压 / V',0,24,12],['resistance','电阻 / Ω',1,100,24]],buttons:[['switch','开关：闭合']],note:'理想电源与电阻模型：I = U / R，P = U² / R；忽略电源内阻与温度变化。'},
 {id:'solar-orbits',style:'neon',title:'太阳系轨道漫游',topic:'3D霓虹太阳系模型，拖动旋转、调节时间速度并点击地球与火星查看轨道运动',summary:'旋转空间视角，比较行星绕太阳的运动。',accent:'#a693ff',bg:'#100e27',ink:'#f1edff',controls:[['speed','时间速度',0,100,25],['rotation','观察角度',-180,180,20]],buttons:[['earth','地球'],['mars','火星']],note:'轨道半径、天体大小与时间均压缩显示，模型不按真实比例。',source:'https://science.nasa.gov/solar-system/'},
 {id:'gear-workshop',style:'clay',title:'齿轮的速度交换',topic:'黏土工坊风格齿轮机构，调节两个齿轮的齿数，观察转向与传动比',summary:'改变齿数，观察从动齿轮的方向和速度。',accent:'#c98464',bg:'#f3e6d7',ink:'#604d43',controls:[['teethA','主动轮齿数',8,40,16],['teethB','从动轮齿数',8,40,32]],note:'理想外啮合齿轮：转向相反，转速比等于齿数比的倒数；忽略摩擦。'},
 {id:'fraction-pieces',style:'paper',title:'把分数拼成整块',topic:'纸艺分数互动，选择分母与分子，观察整体的等分与已选部分并验证分数',summary:'调节等分数量，亲手组合一个分数。',accent:'#df735f',bg:'#fff6e7',ink:'#483f38',controls:[['denominator','等分数量',2,12,4],['numerator','选中份数',0,12,1]],note:'每份必须等大。分子超过分母时，页面会自动限制到一个整体内。'},
 {id:'loop-playground',style:'pixel',title:'亲手执行一次循环',topic:'像素乐园编程循环，设置重复次数，逐步执行并跟踪计数器和累加变量',summary:'单步执行，看到每一次循环怎样改变变量。',accent:'#9fdd8e',bg:'#172a25',ink:'#e9f7e5',controls:[['limit','循环次数',1,12,5]],buttons:[['step','执行一步'],['run','自动执行']],note:'累加从1到n，逐步跟踪 i 与 sum；示例不依赖任何编程环境。'},
 {id:'wave-spectrum',style:'glass',title:'声音的波形实验',topic:'玻璃光谱风格声波交互，改变频率与振幅，观察波形并理解音调和响度的关系',summary:'改变频率和振幅，实时观察波形。',accent:'#766dc9',bg:'#eef0fc',ink:'#383858',controls:[['frequency','频率 / Hz',100,1200,440],['amplitude','振幅（相对量）',0,100,45]],note:'显示的是正弦波示意；未播放声音。频率影响音调，响度也受到听觉与频率等因素影响。'},
 {id:'growth-chart',style:'editorial',title:'增长为什么会放缓',topic:'杂志数据风格逻辑斯蒂增长模型，调节增长率与环境容量，对比限制下的增长曲线',summary:'调节环境容量，看增长曲线如何变化。',accent:'#b65747',bg:'#f9f6ef',ink:'#302f2e',controls:[['rate','增长率 r / 步',1,30,12],['capacity','环境容量 K',100,1000,500]],note:'离散逻辑斯蒂教学模型，初始数量20，每步 N ← N + rN(1−N/K)；不用于实际人口预测。'},
 {id:'coin-probability',style:'minimal',title:'概率与频率小实验',topic:'极简硬币概率实验，可设置正面概率并投掷1次、100次，观察经验频率与理论概率',summary:'重复试验，比较理论概率和实验频率。',accent:'#668695',bg:'#f8faf9',ink:'#334149',controls:[['probability','正面概率 / %',0,100,50]],buttons:[['once','投掷 1 次'],['hundred','投掷 100 次']],note:'每次使用独立随机数；有限次数的频率可能偏离理论概率。'},
];
