import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoundedBoxGeometry} from 'three/addons/geometries/RoundedBoxGeometry.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
const TAU=Math.PI*2;
export function createExperience({canvas,C,state,get}){
 const painted=['ink','watercolor'].includes(C.style), editorial=C.style==='editorial';
 if(painted||editorial){createPainting({canvas,C,state,get});return;}
 let renderer;try{renderer=new T.WebGLRenderer({canvas,antialias:true,alpha:false,preserveDrawingBuffer:true});}catch{document.getElementById('scene-status').textContent='设备未启用三维渲染 · 参数实验仍可操作';createPainting({canvas:canvas.parentNode.appendChild(document.createElement('canvas')),C,state,get});return;}
 renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.8));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=C.style==='neon'?1.1:.9;
 const scene=new T.Scene();scene.background=new T.Color(C.bg);const camera=new T.PerspectiveCamera(35,1,.05,100);camera.position.set(5.5,4.2,7.5);const controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.minDistance=3;controls.maxDistance=16;controls.target.set(0,.65,0);controls.enablePan=false;controls.maxPolarAngle=Math.PI*.49;
 const environment=new RoomEnvironment();const pmrem=new T.PMREMGenerator(renderer);const env=pmrem.fromScene(environment,.04);scene.environment=env.texture;scene.environmentIntensity=.6;environment.dispose();pmrem.dispose();
 const ambient=new T.HemisphereLight(0xdce9ff,0x222531,.45);scene.add(ambient);const light=new T.DirectionalLight(0xffe5c4,2.8);light.position.set(3,7,4);light.castShadow=true;light.shadow.mapSize.set(1024,1024);Object.assign(light.shadow.camera,{left:-5,right:5,top:5,bottom:-5,near:.1,far:20});light.shadow.bias=-.0005;light.shadow.normalBias=.025;scene.add(light);
 const rim=new T.DirectionalLight(C.accent,1.3);rim.position.set(-4,3,-3);scene.add(rim);
 const root=new T.Group();scene.add(root);const animated=[];const clickable=[];let rebuild=null;
 function mat(color,metalness=0,roughness=.45){return new T.MeshStandardMaterial({color,metalness,roughness});}
 function mesh(geo,m,p=[0,0,0],parent=root){const o=new T.Mesh(geo,m);o.position.set(...p);o.castShadow=o.receiveShadow=true;parent.add(o);return o;}
 function box(w,h,d,m,p,parent){return mesh(new RoundedBoxGeometry(w,h,d,3,Math.min(w,h,d)*.08),m,p,parent);}
 function ball(r,m,p,scale=[1,1,1],parent){const o=mesh(new T.SphereGeometry(r,40,28),m,p,parent);o.scale.set(...scale);return o;}
 function cylinder(r,h,m,p,parent){const b=Math.min(.035,h*.12,r*.08),points=[new T.Vector2(0,-h/2),new T.Vector2(r-b,-h/2),new T.Vector2(r,-h/2+b),new T.Vector2(r,h/2-b),new T.Vector2(r-b,h/2),new T.Vector2(0,h/2)];return mesh(new T.LatheGeometry(points,96),m,p,parent);}
 function tube(points,r,m,parent=root){return mesh(new T.TubeGeometry(new T.CatmullRomCurve3(points.map(p=>new T.Vector3(...p))),64,r,10,false),m,[0,0,0],parent);}
 function torus(r,t,m,p,parent){const o=mesh(new T.TorusGeometry(r,t,12,80),m,p,parent);o.rotation.x=Math.PI/2;return o;}
 const floor=mesh(new T.PlaneGeometry(100,100),mat(C.style==='simulation'?'#1c252c':C.bg,0,.85),[0,-.18,0],scene);floor.rotation.x=-Math.PI/2;
 function plinth(){cylinder(2.4,.18,mat(C.style==='simulation'?'#303941':'#e5dfd5',.2,.6),[0,-.06,0]);}
 const copper=mat('#b96939',.83,.26),steel=mat('#8898a6',.95,.24),dark=mat('#24313a',.7,.33);
 if(C.id==='electric-motor'){
 plinth();const assembly=new T.Group();assembly.rotation.x=.38;root.add(assembly);
 const housing=mesh(new T.CylinderGeometry(1.38,1.38,1.45,80,1,true,Math.PI*.20,Math.PI*1.55),steel,[0,.95,0],assembly);housing.material.side=T.DoubleSide;
 for(let k=0;k<10;k++){const ring=mesh(new T.CylinderGeometry(1.42,1.42,.035,80,1,true,Math.PI*.2,Math.PI*1.55),dark,[0,.35+k*.13,0],assembly);ring.material.side=T.DoubleSide;}
 for(let i=0;i<18;i++){const q=i/18*TAU,x=Math.cos(q),z=Math.sin(q);const slot=box(.2,1.28,.2,dark,[x*1.13,.96,z*1.13],assembly);slot.rotation.y=-q;for(let j=0;j<5;j++){const winding=torus(.12,.025,copper,[x*1.08,.5+j*.2,z*1.08],assembly);winding.scale.set(1,1,1.7);}}
 const rotor=new T.Group();assembly.add(rotor);cylinder(.72,1.3,steel,[0,.95,0],rotor);cylinder(.17,2.6,steel,[0,1.1,0],rotor);for(let i=0;i<8;i++){const q=i/8*TAU;const magnet=box(.4,1.1,.15,mat(i%2?'#d25f4c':'#5595a8',.65,.3),[Math.cos(q)*.7,.95,Math.sin(q)*.7],rotor);magnet.rotation.y=-q+Math.PI/2;}
 for(let i=0;i<8;i++){const q=i/8*TAU;cylinder(.055,.08,steel,[Math.cos(q)*1.3,.22,Math.sin(q)*1.3],assembly);}
 box(.6,.4,.6,dark,[1.5,.7,-.3],assembly);for(let i=0;i<3;i++)tube([[1.5,.8,-.3],[1.8,.7,-.3+i*.1],[2.1,.2,-.3+i*.1]],.035,mat(['#ffb064','#698eb1','#c9cfd3'][i]),assembly);
 animated.push(t=>{rotor.rotation.y=t*(state.direction<0?-1:1)*state.speed*.04;});camera.position.set(4.3,4.6,5.8);
 }
 else if(C.id==='human-layers'){
 controls.target.set(0,1.35,0);camera.position.set(3,2.5,6.4);const body=new T.Group();root.add(body);const ivory=mat('#e6d4b4',.05,.48),skin=new T.MeshPhysicalMaterial({color:'#81bbb7',roughness:.3,transparent:true,opacity:.14,depthWrite:false,side:T.DoubleSide});const skeleton=new T.Group(),organs=new T.Group(),shell=new T.Group();body.add(skeleton,organs,shell);
 ball(.24,ivory,[0,2.65,0],[.8,1.1,.85],skeleton);if(C.body){const geom=new T.BufferGeometry();const positions=C.body.positions.map((v,i)=>i%3===0?-C.body.positions[i+2]*.75:i%3===1?v*.51+1.42:C.body.positions[i-2]*.3);geom.setAttribute('position',new T.Float32BufferAttribute(positions,3));geom.setIndex(C.body.indices);geom.computeVertexNormals();mesh(geom,skin,[0,0,0],shell);}else{ball(.25,skin,[0,2.65,0],[.87,1.2,.92],shell);ball(.54,skin,[0,1.75,0],[.75,1.35,.47],shell);}
 tube([[0,1.05,0],[0,1.6,-.06],[0,2.35,0]],.035,ivory,skeleton);
 for(let i=0;i<10;i++){let y=2.15-i*.055,w=.24+Math.sin(i/10*Math.PI)*.11;for(const side of [-1,1])tube([[0,y,-.02],[side*w,y,.02],[side*w*.8,y-.07,.19],[0,y-.06,.22]],.015,ivory,skeleton);}
 for(const s of [-1,1]){tube([[s*.11,2.3,0],[s*.46,2.19,0],[s*.55,1.66,0],[s*.66,1.2,.03]],.032,ivory,skeleton);ball(.085,ivory,[s*.55,1.66,0],[1,1,1],skeleton);tube([[s*.16,1.07,0],[s*.19,.56,0],[s*.2,.06,.06]],.04,ivory,skeleton);if(!C.body){ball(.22,skin,[s*.52,1.7,0],[.4,2.7,.43],shell);ball(.27,skin,[s*.18,.57,0],[.46,2.05,.5],shell);}ball(.08,ivory,[s*.2,.55,0],[1,1,1],skeleton);}
 torus(.21,.03,ivory,[0,1.15,0],skeleton);
 function organ(name,geo,color,p,scale){const m=mat(color,.05,.34),o=mesh(geo,m,p,organs);o.scale.set(...scale);o.userData.organ=name;clickable.push(o);return o;}
 const lungGeo=new T.SphereGeometry(1,48,36);const position=lungGeo.attributes.position;for(let i=0;i<position.count;i++){const y=position.getY(i),x=position.getX(i);position.setX(i,x*(.78-.18*y));}lungGeo.computeVertexNormals();organ('lungs',lungGeo,'#bf9385',[-.20,1.91,.14],[.19,.36,.16]);organ('lungs',lungGeo,'#bf9385',[.20,1.91,.14],[.19,.36,.16]);
 const heartShape=new T.Shape();heartShape.moveTo(0,0);heartShape.bezierCurveTo(-.4,.4,-.65,-.05,0,-.7);heartShape.bezierCurveTo(.65,-.05,.4,.4,0,0);const heart=organ('heart',new T.ExtrudeGeometry(heartShape,{depth:.16,bevelEnabled:true,bevelSize:.08,bevelThickness:.08,bevelSegments:5,steps:1}),'#a64340',[.08,1.91,.29],[.22,.27,.7]);heart.rotation.z=-.25;
 organ('liver',new T.SphereGeometry(1,40,24),'#775143',[-.12,1.46,.17],[.32,.13,.18]);organ('stomach',new T.TorusGeometry(.13,.07,20,40,Math.PI*1.65),'#d49f93',[.18,1.43,.2],[1,1.3,.8]);for(let i=0;i<5;i++)tube([[-.18,1.28-i*.045,.2],[.18,1.26-i*.045,.23],[.18,1.2-i*.045,.2],[-.18,1.22-i*.045,.23]],.025,mat('#ae8e75'),organs);
 tube([[0,2.3,.12],[0,2.05,.16],[-.16,1.93,.22]],.026,ivory,organs);tube([[0,2.05,.16],[.16,1.93,.22]],.025,ivory,organs);
 const platform=cylinder(.9,.1,dark,[0,-.12,0]);platform.material=mat('#1f393d',.6,.28);
 animated.push(()=>{const g=get();organs.visible=g.layer==='organs';skeleton.visible=g.layer!=='skin';shell.visible=true;skin.opacity=g.layer==='skin'?.7:state.opacity/100*.5+.06;body.rotation.y=g.angle;clickable.forEach(o=>o.material.emissive.set(o.userData.organ===g.selected?'#351610':'#000000'));});
 canvas.addEventListener('click',e=>{const r=canvas.getBoundingClientRect(),ray=new T.Raycaster();ray.setFromCamera(new T.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);const hit=ray.intersectObjects(clickable)[0];if(hit)document.querySelector('[data-organ='+hit.object.userData.organ+']')?.click();});
 }
 else if(C.id==='solar-orbits'){
 scene.background=new T.Color('#090a19');floor.visible=false;light.intensity=0;ambient.intensity=.3;camera.position.set(5,5,8);controls.target.set(0,0,0);const sun=ball(.52,new T.MeshBasicMaterial({color:'#ffbe62'}),[0,0,0]);const glow=ball(.6,new T.MeshBasicMaterial({color:'#ef872f',transparent:true,opacity:.18,side:T.BackSide}),[0,0,0]);scene.add(new T.PointLight('#ffdb9b',65,30,2));
 const textureCanvas=document.createElement('canvas');textureCanvas.width=512;textureCanvas.height=256;const ct=textureCanvas.getContext('2d');ct.fillStyle='#204965';ct.fillRect(0,0,512,256);for(let i=0;i<1000;i++){const x=(Math.sin(i*728.31)+1)*256,y=(Math.sin(i*12.93)+1)*128;ct.fillStyle=i%4?'#547966':'#adbbb3';ct.globalAlpha=.4;ct.beginPath();ct.ellipse(x,y,3+(i%13),2+(i%9),i,0,TAU);ct.fill();}ct.globalAlpha=1;ct.fillStyle='#d2dddd';ct.fillRect(0,0,512,10);ct.fillRect(0,243,512,13);const tex=new T.CanvasTexture(textureCanvas);tex.colorSpace=T.SRGBColorSpace;
 const earth=ball(.20,new T.MeshStandardMaterial({map:tex,roughness:.75}),[2,0,0]);ball(.214,new T.MeshPhysicalMaterial({color:'#88caff',transparent:true,opacity:.12,roughness:.2}),[0,0,0],[1,1,1],earth);const mars=ball(.14,mat('#b76440',0,.9),[3.1,0,0]);
 for(const r of [1.1,2,3.1]){const ring=torus(r,.004,new T.MeshBasicMaterial({color:'#524f76'}),[0,0,0]);ring.castShadow=false;}
 const points=[];for(let i=0;i<1600;i++){const a=i*2.39996,z=1-i/800,r=Math.sqrt(Math.max(0,1-z*z));points.push(Math.cos(a)*r*35,z*35,Math.sin(a)*r*35);}const stars=new T.BufferGeometry();stars.setAttribute('position',new T.Float32BufferAttribute(points,3));scene.add(new T.Points(stars,new T.PointsMaterial({color:'#dddffb',size:.065,sizeAttenuation:true})));
 animated.push(t=>{earth.position.set(Math.cos(t*.13)*2,0,Math.sin(t*.13)*2);earth.rotation.y=t*.15;mars.position.set(Math.cos(t*.07)*3.1,0,Math.sin(t*.07)*3.1);glow.scale.setScalar(1+Math.sin(t)*.03);root.rotation.y=get().angle*.1;earth.material.emissive.set(get().selected==='earth'?'#123446':'#000000');mars.material.emissive.set(get().selected==='mars'?'#462516':'#000000');});
 }
 else if(C.id==='gear-workshop'){
 plinth();const gears=new T.Group();root.add(gears);let last='';function gear(n,r,col,x){const shape=new T.Shape();for(let i=0;i<n*4;i++){const a=i/(n*4)*TAU,rr=r+(i%4<2?.09:0);i?shape.lineTo(Math.cos(a)*rr,Math.sin(a)*rr):shape.moveTo(Math.cos(a)*rr,Math.sin(a)*rr);}shape.closePath();const hole=new T.Path();hole.absarc(0,0,.15,0,TAU,true);shape.holes.push(hole);const o=mesh(new T.ExtrudeGeometry(shape,{depth:.25,bevelEnabled:true,bevelSize:.035,bevelThickness:.035,bevelSegments:3,steps:1}),mat(col,0,.68),[x,.2,0],gears);o.rotation.x=-Math.PI/2;cylinder(.1,.48,mat('#b49c85'),[x,.2,0]);return o;}
 let ga,gb;animated.push(t=>{const key=state.teethA+','+state.teethB;if(last!==key){for(const o of [...gears.children]){o.geometry.dispose();o.material.dispose();gears.remove(o);}const a=state.teethA*.032,b=state.teethB*.032;ga=gear(state.teethA,a,'#c98266',-a-.04);gb=gear(state.teethB,b,'#8cb6a5',b+.04);last=key;}ga.rotation.z=t*.5;gb.rotation.z=-t*.5*state.teethA/state.teethB;});camera.position.set(3.3,5,5);
 }
 else if(C.id==='fraction-pieces'){
 const pieces=new T.Group();root.add(pieces);const base=cylinder(1.65,.08,mat('#dfccae',0,.9),[0,0,0]);let last='';animated.push(()=>{const key=state.denominator+','+state.numerator;if(last===key)return;last=key;for(const p of [...pieces.children]){p.geometry.dispose();p.material.dispose();pieces.remove(p);}for(let i=0;i<state.denominator;i++){const start=i/state.denominator*TAU+.02,end=(i+1)/state.denominator*TAU-.02,shape=new T.Shape();shape.moveTo(0,0);shape.absarc(0,0,1.5,start,end,false);shape.lineTo(0,0);const selected=i<state.numerator,p=mesh(new T.ExtrudeGeometry(shape,{depth:.035,bevelEnabled:false}),mat(selected?['#da6b52','#edae69','#d99782'][i%3]:'#f7ecd4',0,.95),[Math.cos((start+end)/2)*(selected?.07:0),selected?.10:.05,Math.sin((start+end)/2)*(selected?.07:0)],pieces);p.rotation.x=-Math.PI/2;}});camera.position.set(2.2,5,4);
 }
 else if(C.id==='circuit-lab'){
 light.intensity=1;ambient.intensity=1;const grid=new T.GridHelper(10,40,'#337090','#17415e');grid.position.y=-.15;scene.add(grid);floor.visible=false;const cyan=new T.MeshStandardMaterial({color:'#79dfff',emissive:'#277b97',emissiveIntensity:.6,wireframe:true});box(3.8,.18,2.6,cyan,[0,0,0]);box(.55,.55,.9,mat('#284b69',.5,.4),[-1.3,.35,0]);for(let i=0;i<9;i++)box(.06,.58,.05,cyan,[-1.6+i*.07,.35,.44]);const resistor=cylinder(.2,.8,mat('#b6bcb2'),[1.3,.35,0]);resistor.rotation.z=Math.PI/2;for(let i=0;i<4;i++){const r=torus(.205,.022,mat(['#be784b','#36343e','#dc6353','#bd964b'][i]),[1.04+i*.15,.35,0]);r.rotation.z=Math.PI/2;}
 const wire=new T.MeshBasicMaterial({color:'#82ddff'});tube([[-1.3,.55,-.35],[-1.3,.1,-.9],[1.3,.1,-.9],[1.3,.35,0]],.025,wire);tube([[1.3,.35,0],[1.3,.1,.9],[-1.3,.1,.9],[-1.3,.55,.35]],.025,wire);const particle=ball(.065,new T.MeshBasicMaterial({color:'#ffffff'}),[0,.1,-.9]);const switchArm=box(.5,.055,.09,steel,[0,.2,.9]);animated.push(t=>{particle.visible=get().closed&&state.voltage>0;particle.position.x=Math.sin(t*state.voltage/state.resistance*2)*1.25;switchArm.rotation.z=get().closed?0:.6;});
 }
 else if(C.id==='loop-playground'){
 scene.background=new T.Color('#172e28');const ground=box(4,.15,3,mat('#50644b',0,.95),[0,-.08,0]);for(let i=0;i<50;i++){const x=(i%10)*.4-1.8,z=Math.floor(i/10)*.6-1.2;box(.35,.05,.5,mat(i%3?'#53734f':'#466d49',0,1),[x,.025,z]);}const blocks=[];for(let i=0;i<12;i++)blocks.push(box(.38,.17,.38,mat('#608962'),[-1.4+(i%6)*.55,.13,-.4+Math.floor(i/6)*.8]));const robot=new T.Group();root.add(robot);box(.22,.3,.22,mat('#e7cb87'),[0,.3,0],robot);box(.32,.22,.28,mat('#99d0ba'),[0,.56,0],robot);for(const s of [-1,1]){box(.045,.05,.015,mat('#22382f'),[s*.075,.58,.15],robot);box(.08,.18,.1,mat('#aaaf8a'),[s*.09,.07,0],robot);}
 animated.push(t=>{const g=get();blocks.forEach((b,i)=>{b.visible=i<state.limit;b.material.color.set(i<g.step?'#d1b961':'#537d60');b.scale.y=i<g.step?2:1;});robot.position.set(-1.4+(g.step%6)*.55,Math.sin(t*2)*.025,-.4+Math.floor(Math.min(g.step,11)/6)*.8);});
 }
 else if(C.id==='wave-spectrum'){
 const glass=new T.MeshPhysicalMaterial({color:'#c8c4f2',metalness:.05,roughness:.1,transmission:.8,thickness:.3,ior:1.48});box(4.2,.13,2,glass,[0,0,0]);for(let i=0;i<7;i++){const p=box(.15,1.5,.15,glass,[-1.8+i*.6,.9,-.6]);p.rotation.z=.15;}
 const wave=new T.Group();root.add(wave);const waveMat=mat('#7565bd',.25,.25);const beads=[];for(let i=0;i<120;i++)beads.push(ball(.024,waveMat,[-2+i/30,1,0]));animated.push(t=>{beads.forEach((b,i)=>b.position.y=1+Math.sin(i/120*state.frequency/180*TAU-t)*state.amplitude*.009);});camera.position.set(4,3.3,6.5);
 }
 else{
 const coin=new T.Group();root.add(coin);const gold=mat('#c9b585',.85,.3);const disk=cylinder(.65,.10,gold,[0,1,0],coin);disk.rotation.x=Math.PI/2;for(let i=0;i<80;i++){let a=i/80*TAU;const ridge=box(.014,.035,.12,gold,[Math.cos(a)*.64,1+Math.sin(a)*.64,0],coin);ridge.rotation.z=a;}
 const inner=torus(.51,.013,gold,[0,1,.056],coin);inner.rotation.x=0;const bars=[];for(let i=0;i<24;i++)bars.push(box(.12,.1,.12,mat(i%2?'#bdcbd0':'#9bacb2',.25,.5),[-1.5+i*.13,0,-.8]));animated.push(t=>{const g=get();coin.rotation.y=g.tosses?Math.sin(t*.4)*.2:0;bars.forEach((b,i)=>{const h=.1+(g.tosses?g.heads/Math.max(1,g.tosses):.5)*(i%2?1.3:.8);b.scale.y=h/.1;b.position.y=h/2;});});camera.position.set(3.8,3.8,6);}
 const resize=()=>{const w=canvas.clientWidth||800,h=canvas.clientHeight||600;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();};new ResizeObserver(resize).observe(canvas);resize();let time=0,last=0;const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;
 function tick(ms){const dt=Math.min(.05,(ms-last)/1000||0);last=ms;if(!document.hidden){if(document.getElementById('pause').textContent==='暂停演示'&&!reduce)time+=dt*(C.id==='solar-orbits'?state.speed/25:1);animated.forEach(f=>f(time));controls.update();renderer.render(scene,camera);document.body.dataset.ready='true';}requestAnimationFrame(tick);}requestAnimationFrame(tick);
 document.getElementById('scene-status').textContent='实时三维 · 拖动旋转 / 滚轮缩放';document.getElementById('reset').addEventListener('click',()=>{time=0;controls.reset();});controls.saveState();canvas.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','+','-'].includes(e.key)){e.preventDefault();const offset=camera.position.clone().sub(controls.target);if(e.key==='+'||e.key==='-')offset.multiplyScalar(e.key==='+'?.9:1.1);else offset.applyAxisAngle(new T.Vector3(0,1,0),e.key==='ArrowLeft'?.12:-.12);camera.position.copy(controls.target).add(offset);controls.update();}});
 document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{const name=b.dataset.view,c=name==='top'?[.01,8,.01]:name==='front'?[0,1.8,7]:[5.5,4.2,7.5];camera.position.set(...c);controls.update();document.querySelectorAll('[data-view]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));}));
}
function createPainting({canvas,C,state,get}){
 canvas.style.width='100%';canvas.style.height='100%';const ctx=canvas.getContext('2d');if(!ctx)return;const image=new Image();image.src=C.art||C.fallback||'';let time=0,last=0;const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;
 function draw(ms){const dt=Math.min(.05,(ms-last)/1000||0);last=ms;if(document.hidden){requestAnimationFrame(draw);return;}if(document.getElementById('pause').textContent==='暂停演示'&&!reduce)time+=dt;const w=canvas.clientWidth||800,h=canvas.clientHeight||600,d=Math.min(devicePixelRatio||1,2);if(canvas.width!==w*d||canvas.height!==h*d){canvas.width=w*d;canvas.height=h*d;}ctx.setTransform(d,0,0,d,0,0);ctx.fillStyle=C.bg;ctx.fillRect(0,0,w,h);
 if(image.complete&&image.naturalWidth){const ratio=Math.max(w/image.width,h/image.height),iw=image.width*ratio,ih=image.height*ratio;ctx.drawImage(image,(w-iw)/2,(h-ih)/2,iw,ih);}
 if(C.style==='ink'){ctx.strokeStyle='#3e594a55';ctx.lineWidth=.7;for(let i=0;i<state.rain*.65;i++){const x=(Math.sin(i*72.31)+1)*w/2,y=(i*97+time*140)%h;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-3,y+13);ctx.stroke();}for(let i=0;i<state.sun*.25;i++){const x=w*.4+(i%8)*w*.047,y=h*.84-((time*22+i*35)%(h*.38));const g=ctx.createRadialGradient(x,y,1,x,y,20);g.addColorStop(0,'#ffffff55');g.addColorStop(1,'#ffffff00');ctx.fillStyle=g;ctx.fillRect(x-20,y-20,40,40);}ctx.strokeStyle='#647d7355';for(let i=0;i<8;i++){const x=w*(.4+i*.06),y=h*(.83+(i%3)*.035);ctx.beginPath();ctx.ellipse(x,y,10+(time*8+i*6)%30,3,0,0,Math.PI*2);ctx.stroke();}}
 else if(C.style==='watercolor'){const rate=Math.min(state.light,state.co2);ctx.globalAlpha=.18+state.light/300;const g=ctx.createRadialGradient(w*.85,h*.16,10,w*.85,h*.16,w*.5);g.addColorStop(0,'#fff3a5');g.addColorStop(1,'#fff3a500');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);ctx.globalAlpha=1;for(let i=0;i<rate*.3;i++){let x=w*(.2+(i%9)*.065),y=h*.85-((time*24+i*31)%(h*.55));ctx.beginPath();ctx.arc(x,y,3+i%4,0,Math.PI*2);ctx.strokeStyle='#689f8155';ctx.stroke();}}
 else if(C.style==='editorial'){ctx.fillStyle='#eee6d8';for(let i=0;i<8;i++){ctx.fillRect(w*.12,h*.2+i*h*.075,w*.78,1);}ctx.strokeStyle='#b65747';ctx.lineWidth=3;ctx.beginPath();let n=20;for(let i=0;i<=80;i++){const x=w*.12+i/80*w*.78,y=h*.82-n/1000*h*.65;if(i)ctx.lineTo(x,y);else ctx.moveTo(x,y);n+=state.rate/100*n*(1-n/state.capacity);}ctx.stroke();ctx.font='italic 90px Georgia';ctx.fillStyle='#302f2e';ctx.fillText('N',w*.09,h*.17);ctx.font='12px system-ui';ctx.fillStyle='#7f7467';ctx.fillText('LIMITS TO GROWTH',w*.3,h*.13);ctx.fillText('0',w*.1,h*.87);ctx.fillText('80 模拟步',w*.79,h*.87);ctx.setLineDash([4,6]);ctx.strokeStyle='#8a9785';ctx.beginPath();ctx.moveTo(w*.12,h*.82-state.capacity/1000*h*.65);ctx.lineTo(w*.9,h*.82-state.capacity/1000*h*.65);ctx.stroke();ctx.setLineDash([]);ctx.fillText('K = '+state.capacity,w*.75,h*.8-state.capacity/1000*h*.65);}
 document.body.dataset.ready='true';requestAnimationFrame(draw);}requestAnimationFrame(draw);document.getElementById('scene-status').textContent=C.style==='editorial'?'实时计算 · 调节参数比较曲线':'绘画场景 · 调节参数观察变化';
}
