import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {transformSync} from 'esbuild';
import vm from 'node:vm';
function store(){const module={exports:{}};vm.runInNewContext(transformSync(readFileSync(new URL('../src/tasks/store.ts',import.meta.url),'utf8'),{loader:'ts',format:'cjs'}).code,{module,crypto,Date});return module.exports;}
test('one pipeline card spans child requests, real progress and completion',()=>{const s=store(),c=new AbortController();let changes=0;const unsub=s.subscribeTasks(()=>changes++);const card=s.beginTask(c,{toolId:'board',title:'diagram'});assert.ok(s.hasTask(c.signal));s.beginTask(c,{toolId:'board',title:'nested'}).finish();assert.equal(s.taskSnapshot().length,1);s.updateTask(c.signal,{stage:'drawing',done:2,total:5});assert.equal(s.taskSnapshot()[0].done,2);card.finish();assert.equal(s.taskSnapshot()[0].state,'done');assert.ok(!s.hasTask(c.signal));card.finish('late failure');assert.equal(s.taskSnapshot()[0].state,'done');assert.ok(changes>=3);unsub();});
test('cancel only selected task; retain stopping until saving settles; clear does not delete live jobs',()=>{const s=store(),a=new AbortController(),b=new AbortController();const first=s.beginTask(a,{toolId:'cover',title:'a'});s.beginTask(b,{toolId:'comic',title:'b'});s.cancelTask(s.taskSnapshot()[1].id);assert.equal(a.signal.aborted,true);assert.equal(b.signal.aborted,false);assert.equal(s.taskSnapshot()[1].state,'stopping');s.clearFinishedTasks();assert.equal(s.taskSnapshot().length,2);first.finish();assert.equal(s.taskSnapshot()[1].state,'cancelled');s.clearFinishedTasks();assert.equal(s.taskSnapshot().length,1);s.cancelAllTasks();assert.equal(b.signal.aborted,true);});
test('caught pipeline errors and disk failures never show as completed',()=>{const s=store(),c=new AbortController();const card=s.beginTask(c,{toolId:'comic',title:'a'});s.failTask(c.signal,'disk full');card.finish();assert.equal(s.taskSnapshot()[0].state,'error');assert.equal(s.taskSnapshot()[0].error,'disk full');});
test('bounded history preserves all running tasks',()=>{const s=store(),live=new AbortController();s.beginTask(live,{toolId:'board',title:'live'});for(let i=0;i<105;i++)s.beginTask(new AbortController(),{toolId:'cover',title:''}).finish();assert.equal(s.taskSnapshot().length,101);assert.ok(s.hasTask(live.signal));});
test('submitted publication cannot pretend to cancel while the site may have accepted it',()=>{const s=store(),c=new AbortController();const card=s.beginTask(c,{toolId:'comic',title:'publish',cancellable:false});s.cancelTask(s.taskSnapshot()[0].id);s.cancelAllTasks();assert.equal(c.signal.aborted,false);assert.equal(s.taskSnapshot()[0].state,'running');card.finish();assert.equal(s.taskSnapshot()[0].state,'done');});
