import {test} from 'node:test';
import assert from 'node:assert/strict';
import {buildSync} from 'esbuild';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
function load(file){const module={exports:{}};vm.runInNewContext(buildSync({entryPoints:[`src/course/${file}.ts`],bundle:true,write:false,platform:'node',format:'cjs'}).outputFiles[0].text,{module,structuredClone});return module.exports;}
const m=load('model'),{runWorkflow}=load('workflow'),examples=load('examples');
const plan=(count=4)=>({title:'检验理解',analysis:'理解概念、视觉图解、步骤练习',summary:'能用自己的话解释知识',pages:Array.from({length:count},(_,i)=>({title:`概念${i}`,text:['用自己的话讲清楚'],visual:`第${i}张独立图解`} ))});
const ref=i=>'workstore-image:'+String(i).repeat(64);
function harness(extra={}){let current={...m.emptyContent(),config:{...m.defaults(),topic:'学习方法'}},valid=true,serial=0;const saves=[],images=[],abort=new AbortController();return {get current(){return current;},saves,images,abort,invalidate(){valid=false;},deps:{valid:()=>valid,text:async()=>JSON.stringify(plan()),image:async(prompt,refs)=>{const n=++serial;images.push({prompt,refs,n});return extra.image?extra.image(prompt,refs,n):ref(n);},save:async c=>{if(extra.failSave)throw Error('磁盘满');current=structuredClone(c);saves.push(current);}}};}
test('official upstream source hashes and twelve styles/eight layouts load unchanged',()=>{const root='vendor/baoyu-xhs-images/',meta=JSON.parse(readFileSync(root+'UPSTREAM.json'));for(const [path,hash]of Object.entries(meta.sha256))assert.equal(createHash('sha256').update(readFileSync(root+path)).digest('hex'),hash,path);assert.equal(m.styles.length,12);assert.equal(m.layouts.length,8);assert.match(m.planningPrompt({...m.defaults(),topic:'解释重力'}),/Content Analysis|Content Type|content type|内容/);});
test('plan enforces count, readable text, unique content and known configuration',()=>{const c={...m.defaults(),topic:'学习方法'};assert.equal(m.parsePlan(JSON.stringify(plan()),c).pages.length,4);assert.throws(()=>m.parsePlan(JSON.stringify(plan(3)),c));const bad=plan();bad.pages[1]=bad.pages[0];assert.throws(()=>m.parsePlan(JSON.stringify(bad),c));bad.pages[1]={...bad.pages[0],title:'other',text:['a'.repeat(91)]};assert.throws(()=>m.parsePlan(JSON.stringify(bad),c));assert.throws(()=>m.validateConfig({...c,count:11}));assert.throws(()=>m.validateConfig({...c,topic:''}));assert.throws(()=>m.readContent(JSON.stringify({...m.emptyContent(),config:{...c,style:'unknown'}})));});
test('saves all final prompts before cover; every later card references cover and checkpoints survive',async()=>{const h=harness();const image=h.deps.image;h.deps.image=async(...args)=>{assert.ok(h.current.plan.pages.every(p=>p.prompt));assert.equal(h.current.engine,m.engine);return image(...args);};await runWorkflow(h.current,h.deps,h.abort.signal);assert.equal(h.images[0].refs.length,0);h.images.slice(1).forEach(x=>assert.equal(JSON.stringify(x.refs),JSON.stringify([ref(1)])));assert.equal(h.current.job.status,'done');assert.equal(h.current.plan.pages.filter(p=>p.image).length,4);assert.ok(h.saves.some(c=>c.plan?.pages.filter(p=>p.image).length===1));m.readContent(JSON.stringify(h.current));});
test('failed cover retries once and stops without unanchored content requests',async()=>{const h=harness({image:async()=>{throw Error('service failed');}});await assert.rejects(runWorkflow(h.current,h.deps,h.abort.signal),/封面/);assert.equal(h.images.length,2);assert.equal(h.current.plan.pages[0].status,'error');assert.equal(h.current.plan.pages[1].image,undefined);});
test('partial failure preserves successes and resume only generates failed card',async()=>{let failed=false;const h=harness({image:async(prompt,refs,n)=>{if(prompt.includes('标题：概念1')&&!failed)throw Error('temporary');return ref(n);}});await runWorkflow(h.current,h.deps,h.abort.signal);assert.equal(h.current.job.status,'error');const cover=h.current.plan.pages[0].image,count=h.images.length;failed=true;await runWorkflow(h.current,h.deps,h.abort.signal);assert.equal(h.images.length,count+1);assert.equal(h.current.plan.pages[0].image,cover);assert.equal(h.current.job.status,'done');});
test('cancellation/stale content after image prevents writes, save failure prevents generation',async()=>{const h=harness();h.deps.image=async()=>{h.invalidate();return ref(1);};await assert.rejects(runWorkflow(h.current,h.deps,h.abort.signal));assert.equal(h.current.plan.pages[0].image,undefined);const s=harness({failSave:true});await assert.rejects(runWorkflow(s.current,s.deps,s.abort.signal),/磁盘/);assert.equal(s.images.length,0);});
test('changed config preserves complete prior plan and single-card regeneration saves previous bitmap',async()=>{const h=harness();await runWorkflow(h.current,h.deps,h.abort.signal);const old=h.current.plan.pages[1].image;await runWorkflow(h.current,h.deps,h.abort.signal,1);assert.equal(h.current.plan.pages[1].history[0],old);const c=structuredClone(h.current);c.config.topic='不同主题';await assert.rejects(runWorkflow(c,h.deps,h.abort.signal,1),/设置已改变/);await runWorkflow(c,h.deps,h.abort.signal);assert.equal(h.current.history.length,1);assert.equal(h.current.history[0].config.topic,'学习方法');});
test('eight examples are distinct complete original reference series, not saved documents',()=>{assert.equal(examples.examples.length,8);assert.equal(new Set(examples.examples.map(x=>x.style)).size,8);for(const x of examples.examples){const c=examples.exampleContent(x.id);assert.equal(c.plan.pages.length,5);m.readContent(JSON.stringify(c));assert.ok(c.plan.pages.every(p=>p.prompt&&p.image));assert.equal(c.plannedConfig,m.signature(c.config));}});
test('explicit whole-work regeneration with unchanged preferences renders a new series and archives old cards',async()=>{const h=harness();await runWorkflow(h.current,h.deps,h.abort.signal);const old=h.current.plan.pages[0].image,n=h.images.length;await runWorkflow(h.current,h.deps,h.abort.signal,undefined,true);assert.equal(h.images.length,n+4);assert.equal(h.current.history.length,1);assert.equal(h.current.history[0].plan.pages[0].image,old);assert.notEqual(h.current.plan.pages[0].image,old);});

test('new card prompts prohibit page counters and publication copy preserves editable content',()=>{const config={...m.defaults(),topic:'知识'},c={...m.emptyContent(),config,plan:m.parsePlan(JSON.stringify(plan()),config)};const prompt=m.artPrompt(c,0);assert.doesNotMatch(prompt,/页码：1/);assert.match(prompt,/不添加页码/);const copy=m.publicationCopy(c);assert.ok(copy.description.includes('概念0'));c.copy={...copy,title:'我的发布标题'};assert.equal(m.publicationCopy(c).title,'我的发布标题');m.readContent(JSON.stringify(c));assert.throws(()=>m.readContent(JSON.stringify({...c,copy:{...copy,hashtags:['a'.repeat(31)]}})));});
