import {test,after} from 'node:test';
import assert from 'node:assert/strict';
import {buildSync} from 'esbuild';
import {createRequire} from 'node:module';
import vm from 'node:vm';
import React,{act} from 'react';
import {JSDOM} from 'jsdom';
import {webcrypto} from 'node:crypto';
const dom=new JSDOM('<!doctype html><body></body>',{url:'http://localhost'});
for(const k of ['window','document','navigator','HTMLElement','Element','Node'])Object.defineProperty(globalThis,k,{value:dom.window[k],configurable:true});globalThis.IS_REACT_ACT_ENVIRONMENT=true;const {createRoot}=await import('react-dom/client'),require=createRequire(import.meta.url);after(()=>dom.window.close());
const code=buildSync({entryPoints:['src/course-animation/AnimationWorkspace.tsx'],bundle:true,write:false,format:'cjs',platform:'node',jsx:'automatic',loader:{'.css':'empty'},external:['./store','../comics/images','react','react/jsx-runtime','antd','@ant-design/icons','@remotion/player','../ai/client','../tasks/store','../workspace','@tauri-apps/api/core','@tauri-apps/api/event','../course/store','../course/export','./TutorialVideo','./media','jszip']}).outputFiles[0].text;
const config={duration:30,style:'clean',audience:'儿童',voice:false};const plan={title:'理解一个概念',summary:'会解释一个概念',scenes:Array.from({length:3},(_,i)=>({title:'阶段'+i,seconds:10,narration:'理解这个概念，先看条件，再看过程，最后用一个例子检验。',points:['条件与过程'],visual:{kind:'flow',labels:['条件','过程','结果'],values:[],note:''}}))};
async function harness(initial){let selected=initial?'a':null,creates=0,request=[],taskStages=[],calls=[],invokeArgs=[],errors=[],controller,resolveText,resolvePrepare,tabChanges=[],progressEvent,doc=initial?{id:'a',content:JSON.stringify(initial)}:undefined;const writes=[];const store={currentDocument:()=>doc,remoteVersion:()=>0,stageDocument:(id,patch)=>{doc={...doc,...patch};writes.push(doc.content);},flushDocument:async()=>{}};
const Input=({autoSize,maxLength,...p})=>React.createElement('input',p);Input.TextArea=p=>React.createElement('textarea',p);const antd={Input,Button:({children,loading,onClick,disabled,...p})=>React.createElement('button',{onClick,disabled:disabled||loading,'aria-label':p['aria-label']},children),Select:()=>null,Switch:()=>null,Modal:()=>null,Progress:()=>null};
const module={exports:{}};vm.runInNewContext(code,{module,window,document,navigator,Blob,crypto:webcrypto,AbortController,structuredClone,require:name=>{if(['react','react/jsx-runtime'].includes(name))return require(name);if(name==='antd')return antd;if(name==='@ant-design/icons')return new Proxy({},{get:()=>()=>null});if(name==='@remotion/player')return {Player:()=>null};if(name==='../ai/client')return {trackAiExecution:async(c,p)=>p,ai:{capabilities:async()=>({text:true}),generate:async input=>{request.push(input);if(input.image)return {images:['workstore-image:'+'e'.repeat(64)]};return new Promise(r=>resolveText=r);}}};if(name==='../tasks/store')return {beginTask:()=>({finish(){}}),failTask(){},updateTask:(_,patch)=>taskStages.push(patch)};if(name==='../workspace')return {native:true};if(name==='@tauri-apps/api/event')return {listen:async(_,handler)=>{progressEvent=handler;return()=>{};}};if(name==='@tauri-apps/api/core')return {invoke:async(name,args)=>{calls.push(name);invokeArgs.push(args);if(name==='prepare_course_animation')return new Promise(r=>resolvePrepare=()=>r({...plan,duration:30,style:'clean',scenes:plan.scenes.map(s=>({...s,audio:'workstore-course-media:'+ 'd'.repeat(64)+'.wav',audioVoice:'kokoro-zh-gentle-v1'}))}));if(name==='render_course_animation')return {video:'workstore-course-media:'+ 'a'.repeat(64)+'.mp4'};}};if(name==='../course/store'||name==='./store')return store;if(name==='../comics/images')return {referenceImage:async x=>x.src};if(name==='../course/export')return {download(){},safeName:s=>s};if(name==='./TutorialVideo')return {TutorialVideo:()=>null};if(name==='./media')return {mediaSource:s=>s,exportMedia(){}};if(name==='jszip')return require(name);throw Error(name);}});
let refresh=()=>{};const host=document.createElement('div');document.body.append(host);const root=createRoot(host);let props={id:initial?'a':null,content:initial,draft:{topic:'一个概念',config},tab:initial?'动画':'偏好',busy:false,opening:false,onDraft(){},onCreate:async c=>{creates++;selected='a';doc={id:'a',content:JSON.stringify(c)};return doc;},isCurrent:id=>selected===id,onController:c=>{if(c)controller=c;props.busy=!!c;refresh();},onTab:t=>{tabChanges.push(t);props.tab=t;refresh();},onUseExample(){},onError:e=>errors.push(String(e))};refresh=()=>root.render(React.createElement(module.exports.default,props));await act(async()=>refresh());
const drain=()=>new Promise(r=>setImmediate(r));return {host,taskStages,tabChanges,writes,calls,invokeArgs,errors,get creates(){return creates;},get requests(){return request.length;},get doc(){return doc;},async start(){await act(async()=>{const b=[...host.querySelectorAll('button')].find(x=>x.textContent==='生成动画教程');b.click();b.click();await drain();});},async remake(){await act(async()=>{const b=[...host.querySelectorAll('button')].find(x=>x.textContent==='换自然配音并重制'||x.textContent==='重新制作视频');b.click();await drain();});},async plan(){await act(async()=>{resolveText({text:JSON.stringify(plan)});await drain();});},async progress(){await act(async()=>{progressEvent({payload:{requestId:invokeArgs[0].requestId,progress:.42,stage:'正在合成讲解配音…'}});await drain();});},async prepare(){await act(async()=>{resolvePrepare();await drain();});},selectAway(){selected='other';},modify(){doc={...doc,content:'new user content'};},cancel(){controller.abort();},async close(){refresh=()=>{};await act(async()=>root.unmount());host.remove();}};
}
test('one durable document and prompt checkpoint precede model; successful render saves final MP4',async()=>{const h=await harness();await h.start();assert.equal(h.creates,1);assert.equal(h.requests,1);assert.equal(h.tabChanges[0],'动画');assert.match(h.host.querySelector('[role=status]').textContent,/动画教程生成中.*正在编写分镜与讲解/);assert.ok(JSON.parse(h.doc.content).animationPrompt);await h.plan();assert.ok(JSON.parse(h.doc.content).animationPlan);await h.progress();assert.match(h.host.querySelector('[role=status]').textContent,/正在合成讲解配音/);assert.equal(h.host.querySelector('progress').value,42);await h.prepare();assert.match(JSON.parse(h.doc.content).animationPlan.video,/workstore-course-media:/);assert.equal(JSON.parse(h.doc.content).job.status,'done');assert.deepEqual(h.errors,[]);await h.close();});
test('editing while planning prevents stale results from overwriting user content',async()=>{const h=await harness();await h.start();h.modify();await h.plan();assert.equal(h.doc.content,'new user content');assert.equal(h.calls.length,0);await h.close();});
test('cancel during voice preparation invokes cancellation and never starts render',async()=>{const h=await harness();await h.start();await h.plan();h.cancel();await h.prepare();assert.ok(h.calls.includes('cancel_course_animation'));assert.equal(h.calls.includes('render_course_animation'),false);assert.equal(JSON.parse(h.doc.content).animationPlan.video,undefined);await h.close();});

test('revoicing an old tutorial preserves the old video and audio without rerunning planning',async()=>{const old={version:1,mode:'animation',config:{topic:'一个概念',style:'notion',layout:'dense',palette:'default',audience:'儿童',count:4,ratio:'16:9'},animationConfig:{...config,voice:true},animationPlannedConfig:{...config,voice:true},animationPlan:{...plan,duration:30,style:'clean',video:'workstore-course-media:'+'c'.repeat(64)+'.mp4',scenes:plan.scenes.map(s=>({...s,audio:'workstore-course-media:'+'b'.repeat(64)+'.wav'}))},history:[]};const h=await harness(old);await h.remake();assert.equal(h.requests,0);assert.deepEqual(h.calls,['prepare_course_animation']);await h.prepare();const saved=JSON.parse(h.doc.content);assert.equal(saved.animationHistory.length,1);assert.equal(saved.animationHistory[0].plan.video,old.animationPlan.video);assert.equal(saved.animationHistory[0].plan.scenes[0].audio,old.animationPlan.scenes[0].audio);assert.equal(saved.animationPlan.scenes[0].audioVoice,'kokoro-zh-gentle-v1');assert.deepEqual(h.errors,[]);await h.close();});

test('selected voice overrides planned voice on remake while history keeps original settings',async()=>{const old={version:1,mode:'animation',config:{topic:'一个概念',style:'notion',layout:'dense',palette:'default',audience:'儿童',count:4,ratio:'16:9'},animationConfig:{...config,voice:true,voiceId:'zf_018'},animationPlannedConfig:{...config,voice:true,voiceId:'zf_007'},animationPlan:{...plan,duration:30,style:'clean',video:'workstore-course-media:'+'c'.repeat(64)+'.mp4',scenes:plan.scenes.map(s=>({...s,audio:'workstore-course-media:'+'b'.repeat(64)+'.wav',audioVoice:'kokoro-zh-gentle-v1'}))},history:[]};const h=await harness(old);await h.remake();assert.equal(h.requests,0);assert.equal(h.invokeArgs[0].config.voiceId,'zf_018');await h.prepare();const saved=JSON.parse(h.doc.content);assert.equal(saved.animationHistory[0].config.voiceId,'zf_007');assert.equal(saved.animationPlannedConfig.voiceId,'zf_018');await h.close();});

test('video, audio and cover finish after leaving the document and unmounting its view',async()=>{const h=await harness();await h.start();h.selectAway();await h.close();await h.plan();await h.prepare();const saved=JSON.parse(h.doc.content);assert.equal(saved.job.status,'done');assert.ok(saved.animationPlan.video);assert.equal(saved.cover.status,'done');assert.equal(saved.cover.versions.length,1);assert.equal(h.taskStages.at(-1).stage,'作品及封面已完成');assert.deepEqual(h.errors,[]);assert.equal(h.tabChanges.filter(t=>t==='动画').length,1);});
