import {test,after} from 'node:test';import assert from 'node:assert/strict';import {buildSync} from 'esbuild';import vm from 'node:vm';import fs from 'node:fs';import {createRequire} from 'node:module';import React,{act} from 'react';import {JSDOM} from 'jsdom';import {webcrypto} from 'node:crypto';
const dom=new JSDOM('<body></body>',{url:'http://localhost'});for(const key of ['window','document','navigator','HTMLElement','Element','Node'])Object.defineProperty(globalThis,key,{value:dom.window[key],configurable:true});globalThis.IS_REACT_ACT_ENVIRONMENT=true;const {createRoot}=await import('react-dom/client'),require=createRequire(import.meta.url);after(()=>dom.window.close());
const html=fs.readFileSync('public/course/web/circuit-lab/index.html','utf8'),code=buildSync({entryPoints:['src/course-web/WebWorkspace.tsx'],bundle:true,write:false,format:'cjs',platform:'node',jsx:'automatic',loader:{'.css':'empty'},external:['@tauri-apps/api/core','./store','react','react/jsx-runtime','antd','../ai/client','../tasks/store','../course/store','../course/export','../html/export','../comics/images','./Preview']}).outputFiles[0].text;
async function harness(){let doc,creates=0,requests=0,resolve,selected='a',controller,controllers=[],props;const writes=[],errors=[],tabs=[],store={currentDocument:()=>doc,remoteVersion:()=>0,stageDocument:(id,patch)=>{doc={...doc,...patch};writes.push(JSON.parse(doc.content));},flushDocument:async()=>{}};let refresh=()=>{};
const Input=p=>React.createElement('input',p);Input.TextArea=p=>React.createElement('textarea',p);const antd={Input,Button:({children,onClick,disabled,loading,...p})=>React.createElement('button',{onClick,disabled:disabled||loading,'aria-label':p['aria-label']},children),Select:()=>null,Modal:({open,onCancel,children})=>open?React.createElement('div',{role:'dialog'},React.createElement('button',{onClick:onCancel},'关闭参考'),children):null};const module={exports:{}};vm.runInNewContext(code,{module,document,window,Blob,crypto:webcrypto,AbortController,TextEncoder,structuredClone,fetch:async()=>({ok:true,text:async()=>html}),require(name){if(name==='@tauri-apps/api/core')return {isTauri:()=>false,convertFileSrc:x=>x};if(['react','react/jsx-runtime'].includes(name))return require(name);if(name==='antd')return antd;if(name==='../ai/client')return {trackAiExecution:async(c,p)=>p,ai:{capabilities:async()=>({text:true}),generate:async()=>{requests++;return new Promise(r=>resolve=r);}}};if(name==='../tasks/store')return {beginTask:()=>({finish(){}}),failTask(){},updateTask(){}};if(name==='../course/store'||name==='./store')return store;if(name==='../course/export')return {download(){},safeName:s=>s};if(name==='../html/export')return {exportHtmlFile(){}};if(name==='../comics/images')return {referenceImage:async()=>''};if(name==='./Preview')return ()=>React.createElement('iframe');throw Error(name);}});
const host=document.createElement('div');document.body.append(host);const root=createRoot(host);props={id:null,draft:{topic:'电路实验',config:{style:'blueprint',audience:'青少年',instruction:''}},tab:'偏好',busy:false,opening:false,onDraft(){},onCreate:async c=>{creates++;doc={id:'a',content:JSON.stringify(c)};return doc;},isCurrent:id=>selected===id,onController:(c,owner)=>{controllers.push(c);if(c)controller=c;if(c||controller===owner){props.busy=!!c;refresh();}},onTab:t=>{tabs.push(t);props.tab=t;refresh();},onUseExample(){},onError:e=>errors.push(String(e))};refresh=()=>root.render(React.createElement(module.exports.default,props));await act(async()=>refresh());const drain=()=>new Promise(r=>setImmediate(r));return {writes,tabs,errors,controllers,async referenceCycle(){await act(async()=>{host.querySelector('.course-animation-reference').click();await drain();});assert.ok(host.querySelector('[role=dialog] iframe'));await act(async()=>{[...host.querySelectorAll('button')].find(b=>b.textContent==='关闭参考').click();await drain();});assert.equal(host.querySelector('[role=dialog]'),null);assert.ok(host.querySelector('.course-gallery'));},get creates(){return creates;},get requests(){return requests;},get doc(){return doc;},async start(){await act(async()=>{const b=[...host.querySelectorAll('button')].find(b=>b.textContent==='生成交互网页');b.click();b.click();await drain();});},async complete(){await act(async()=>{resolve({text:html});await drain();});},modify(){doc.content='new content';},cancel(){controller.abort();},async close(){selected='elsewhere';refresh=()=>{};await act(async()=>root.unmount());host.remove();}};}
test('generation creates one local work, switches tab and persists its prompt before model',async()=>{const h=await harness();await h.start();assert.equal(h.creates,1);assert.equal(h.requests,1);assert.equal(h.tabs[0],'作品');assert.equal(h.writes[0].job.status,'running');assert.ok(h.writes[0].webPrompt);await h.complete();assert.equal(h.doc&&JSON.parse(h.doc.content).job.status,'done');assert.match(JSON.parse(h.doc.content).webPlan.html,/电路参数实验台/);assert.deepEqual(h.errors,[]);await h.close();});
test('leaving and unmounting the view keeps generation alive and clears its owner when complete',async()=>{const h=await harness();await h.start();await h.close();await h.complete();assert.equal(JSON.parse(h.doc.content).job.status,'done');assert.equal(h.controllers.at(-1),null);assert.equal(h.tabs.length,1);});
test('late model results cannot overwrite an edited document',async()=>{const h=await harness();await h.start();h.modify();await h.complete();assert.equal(h.doc.content,'new content');await h.close();});
test('stopping a request persists cancellation and never installs its late HTML',async()=>{const h=await harness();await h.start();h.cancel();await h.complete();assert.equal(JSON.parse(h.doc.content).job.status,'cancelled');assert.equal(JSON.parse(h.doc.content).webPlan,undefined);await h.close();});

test('closing a loaded reference preserves the parent workspace',async()=>{const h=await harness();await h.referenceCycle();await h.close();});
