import {test} from 'node:test';import assert from 'node:assert/strict';import {buildSync} from 'esbuild';import vm from 'node:vm';import fs from 'node:fs';
const module={exports:{}};vm.runInNewContext(buildSync({entryPoints:['src/course-whiteboard/model.ts'],bundle:true,format:'cjs',platform:'node',write:false}).outputFiles[0].text,{module});const m=module.exports;const refs=JSON.parse(fs.readFileSync('scripts/course-whiteboard/reference-content.json'));const c=refs[0].config;const plan=m.parsePlan(JSON.stringify({...refs[0],summary:'理解肥皂的作用'}),c);
test('ten complete authored curricula contain two of every duration without filler scenes',()=>{for(const duration of m.durations)assert.equal(refs.filter(r=>r.config.duration===duration).length,2);for(const r of refs){const p=m.parsePlan(JSON.stringify({...r,summary:r.title}),r.config);assert.equal(p.scenes.length*30,r.config.duration);assert.equal(new Set(p.scenes.map(s=>s.narration)).size,p.scenes.length);assert.match(p.srt,/00:00:00,000 -->/);}});
test('integer masks come from actual PNG canvas; narrative event order and closing gaze are protected',()=>{const s=plan.scenes[0],a=m.annotate(s,0,1672,941);m.validateAnnotation(a,s);assert.deepEqual(Array.from(a.elements,e=>e.sequence),[1,2,3,4]);assert.equal(a.elements[2].region.y,470);assert.equal(a.elements[3].region.width,836);assert.equal(a.elements[0].reveal.startMs,300);assert.ok(a.elements.at(-1).reveal.startMs+a.elements.at(-1).reveal.durationMs<=29500);const bad=structuredClone(a);bad.elements[1].reveal.startMs=0;assert.throws(()=>m.validateAnnotation(bad,s));assert.throws(()=>m.annotate(s,0,1024,1024));});
test('SRT uses spoken event timings and complete thirty-second scene span',()=>{const s=structuredClone(plan.scenes[0]);s.captions=m.eventCaptions(s).map(c=>({...c,startMs:Math.round(c.startMs*.98),endMs:Math.round(c.endMs*.98)}));s.captions.at(-1).endMs=30000;const a=m.annotate(s,0,1672,941);m.validateAnnotation(a,s);assert.ok(a.elements[1].reveal.startMs<plan.scenes[0].events[0].text.length/s.narration.length*30000);assert.match(m.toSrt({...plan,scenes:[s]}),/00:00:30,000/);});
test('persisted media paths, narration, unsafe image history and scene counts are validated',()=>{m.validatePlan(plan,c);assert.throws(()=>m.parsePlan(JSON.stringify({...plan,scenes:[]}),c));assert.throws(()=>m.validatePlan({...plan,video:'file:///etc/passwd'},c));const bad=structuredClone(plan);bad.scenes[0].narration='altered';assert.throws(()=>m.validatePlan(bad,c));});

test('styled curricula validate settings and preserve the selected medium in source and inspection prompts',()=>{const styleConfig={...c,style:'watercolor'};m.validateConfig(styleConfig);assert.match(m.imagePrompt(plan.scenes[0],styleConfig),/透明水彩/);assert.doesNotMatch(m.imagePrompt(plan.scenes[0],styleConfig),/不得用绿色/);assert.match(m.inspectionPrompt(plan.scenes[0],1672,941,styleConfig),/透明水彩/);assert.throws(()=>m.validateConfig({...c,style:'unknown'}));assert.match(m.imagePrompt(plan.scenes[0]),/暖米黄/);});

test('style references use ten unique configured media and independent matching covers',()=>{const examples=JSON.parse(fs.readFileSync('src/course-whiteboard/examples.json'));assert.equal(new Set(examples.map(r=>r.config.style)).size,10);for(const r of examples){assert.equal(r.config.style,refs.find(v=>v.id===r.id).config.style);const folder='public/course/whiteboard/'+r.id+'/';assert.ok(!fs.readFileSync(folder+'square-cover.png').equals(fs.readFileSync(folder+'01.png')));assert.ok(fs.existsSync(folder+'square-cover-prompt.md'));const png=fs.readFileSync(folder+'square-cover.png');assert.equal(png.readUInt32BE(16),png.readUInt32BE(20));assert.ok(png.readUInt32BE(16)>=1024);assert.equal(JSON.parse(fs.readFileSync(folder+'style.json')).ratio,'1:1');}const ui=fs.readFileSync('src/course-whiteboard/WhiteboardWorkspace.tsx','utf8');assert.match(ui,/风格参考/);assert.match(ui,/aria-label="沙画绘画风格"/);assert.match(ui,/onUseExample\(\{topic:r.topic,config:r.config\}\)/);});
