import {test} from 'node:test';
import assert from 'node:assert/strict';
import {buildSync} from 'esbuild';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
const module={exports:{}};vm.runInNewContext(buildSync({entryPoints:['src/course-animation/model.ts'],bundle:true,write:false,platform:'node',format:'cjs'}).outputFiles[0].text,{module});const m=module.exports;
const config={duration:30,style:'clean',audience:'儿童',voice:true};
const plan=()=>({title:'理解四分之一',summary:'能识别四分之一',scenes:Array.from({length:3},(_,i)=>({title:'场景'+i,seconds:10,narration:'把一个整体平均分成四份，取其中一份就是四分之一。',points:['平均分','取出一份'],visual:{kind:'fraction',labels:['取一份','共四份'],values:[1,4],note:''}}))});
test('tutorials enforce exact duration, readable labels and valid educational diagrams',()=>{const p=m.parsePlan(JSON.stringify(plan()),config);assert.equal(p.duration,30);const wrong=plan();wrong.scenes[0].seconds=9;assert.throws(()=>m.parsePlan(JSON.stringify(wrong),config),/恰好30/);const bad=plan();bad.scenes[0].visual.values=[5,4];assert.throws(()=>m.parsePlan(JSON.stringify(bad),config),/分数/);const long=plan();long.scenes[0].points=['知识'.repeat(40)];assert.throws(()=>m.parsePlan(JSON.stringify(long),config));});
test('media IDs cannot introduce remote scripts, traversal or foreign voice assets',()=>{const p=m.parsePlan(JSON.stringify(plan()),config);p.scenes[0].audio='https://other.invalid/voice.wav';assert.throws(()=>m.validateTutorial(p,config));p.scenes[0].audio='workstore-course-media:'+ 'a'.repeat(64)+'.wav';p.video='workstore-course-media:'+ 'b'.repeat(64)+'.mp4';m.validateTutorial(p,config);p.video='workstore-course-media:../../x.mp4';assert.throws(()=>m.validateTutorial(p,config));});
test('caption timestamps and SRT preserve scene offsets',()=>{const p=m.parsePlan(JSON.stringify(plan()),config),captions=m.captionsFor(p.scenes[0]);assert.equal(captions[0].startMs,0);assert.equal(captions.at(-1).endMs,10000);assert.match(m.srt(p),/00:00:10,000 -->/);assert.match(m.srt(p),/00:00:30,000/);});
test('ten built-in references include two complete curricula per requested duration',()=>{const refs=JSON.parse(readFileSync('src/course-animation/examples.json'));assert.equal(refs.length,10);for(const seconds of [30,60,120,180,300])assert.equal(refs.filter(x=>x.config.duration===seconds).length,2);for(const ref of refs){const raw=JSON.parse(readFileSync(`public/course/animations/${ref.id}/input.json`));const p=m.parsePlan(JSON.stringify(raw.tutorial),ref.config);assert.equal(p.duration,ref.config.duration);assert.ok(p.scenes.length>=3);}});

test('all twelve audition choices are local, supported and have distinct render profiles',()=>{assert.equal(m.voiceOptions.length,12);const profiles=new Set();for(const v of m.voiceOptions){const c={...config,voiceId:v.value};m.validateConfig(c);assert.equal(m.selectedVoice(c).value,v.value);profiles.add(m.voiceProfile(c));assert.ok(readFileSync('public'+v.sample).length>1000);}assert.equal(profiles.size,12);assert.equal(m.voiceProfile(config),'kokoro-zh-gentle-v1');assert.throws(()=>m.validateConfig({...config,voiceId:'unknown'}));});

test('single caption lines omit surrounding punctuation but retain meaningful internal punctuation',()=>{assert.equal(m.captionText('水一直在旅行。'),'水一直在旅行');assert.equal(m.captionText('如果升温，就关闭加热。'),'如果升温，就关闭加热');const p=m.parsePlan(JSON.stringify(plan()),config);for(const c of m.captionsFor(p.scenes[0]))assert.ok(!/[，。！？；,.!?;]$/.test(c.text));assert.ok(!/就是四分之一。/.test(m.srt(p)));});

test('ten unique animation styles validate, preserve readable diagrams and independent square covers',()=>{const refs=JSON.parse(readFileSync('src/course-animation/examples.json'));assert.equal(new Set(refs.map(r=>r.config.style)).size,10);for(const ref of refs){m.validateConfig(ref.config);const p=JSON.parse(readFileSync('public/course/animations/'+ref.id+'/tutorial.json'));m.validateTutorial(p,ref.config);assert.match(m.prompt(ref.topic,ref.config,'official skill'),/视觉风格/);const png=readFileSync('public'+ref.cover);assert.equal(png.readUInt32BE(16),png.readUInt32BE(20));assert.ok(png.readUInt32BE(16)>=1024);}assert.throws(()=>m.validateConfig({...config,style:'unknown'}));});
