import {test,after} from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {buildSync} from 'esbuild';
import vm from 'node:vm';
import {JSDOM} from 'jsdom';
import React,{act} from 'react';
import {webcrypto} from 'node:crypto';
const dom=new JSDOM('<!doctype html><body></body>',{url:'http://localhost'});
for(const key of ['window','document','navigator','HTMLElement','Element','Node'])Object.defineProperty(globalThis,key,{value:dom.window[key],configurable:true});
globalThis.IS_REACT_ACT_ENVIRONMENT=true;
const {createRoot}=await import('react-dom/client'),require=createRequire(import.meta.url);
after(()=>dom.window.close());
const code=buildSync({entryPoints:['src/course/CourseApp.tsx'],bundle:true,write:false,platform:'node',format:'cjs',jsx:'automatic',loader:{'.css':'empty'},external:['../course-web/WebWorkspace','../course-web/WebPublication','../course-whiteboard/WhiteboardWorkspace','../course-animation/AnimationWorkspace','react','react/jsx-runtime','antd','@ant-design/icons','./store','./export','../ai/client','../tasks/store','../documentLifecycle','../comics/images','../design-studio/images','../story-comic/previewImages','../list-projects/Projects','../story-comic/ComicCanvas','../story-comic/PrintPanel','./Publication']}).outputFiles[0].text;
const drain=()=>new Promise(r=>setImmediate(r));
const config={topic:'一个概念',style:'notion',layout:'dense',palette:'default',audience:'大众学习者',count:4,ratio:'3:4'};
async function harness(empty=false,caps=true){
 let serial=0,creates=0,flushFailure=false,flushWait=null,reads=[],requests=[],listeners=new Set(),blocker;
 const docs=new Map(empty?[]:['a','b'].map(id=>[id,{id,title:id,content:JSON.stringify({version:1,config,history:[]}),lastOpenedAt:id==='a'?2:1}]));
 const store={lastDocumentId:null,documentList:()=>[...docs.values()],currentDocument:id=>docs.get(id),documentWarnings:()=>[],documentStatus:()=>'',subscribe:f=>{listeners.add(f);return()=>listeners.delete(f);},refreshDocuments:async()=>{},flushDocument:async()=>{if(flushFailure)throw Error('保存失败');if(flushWait)await flushWait;},loadDocument:async id=>{reads.push(id);return docs.get(id);},ensureDocument:async id=>docs.get(id),activateDocument:id=>{store.lastDocumentId=id;return docs.get(id);},remoteVersion:()=>0,stageDocument:(id,p)=>{docs.set(id,{...docs.get(id),...p});listeners.forEach(f=>f());},applyDocumentContent:(id,c)=>store.stageDocument(id,{content:c}),createDocument:async()=>{creates++;const d={id:'new-'+ ++serial,title:'未命名',content:''};docs.set(d.id,d);listeners.forEach(f=>f());return d;}};
 const Input=({maxLength,rows,...props})=>React.createElement('input',{...props,maxLength});Input.TextArea=props=>React.createElement('textarea',props);
 const antd={App:{useApp:()=>({message:{success(){}},modal:{confirm(){}}})},Input,Select:({options,value,onChange,disabled,...p})=>React.createElement('select',{'aria-label':p['aria-label'],value,onChange:e=>onChange(e.target.value),disabled},options.map(o=>React.createElement('option',{value:o.value,key:o.value},o.label))),Button:({children,onClick,disabled,loading,...props})=>React.createElement('button',{onClick,disabled:disabled||loading,'aria-label':props['aria-label']},children),Dropdown:({children})=>children,Spin:()=>null,Modal:({open,children,onCancel})=>open?React.createElement('div',{role:'dialog'},React.createElement('button',{onClick:onCancel},'关闭预览'),children):null};
 const module={exports:{}};
 vm.runInNewContext(code,{module,document,window,Blob,structuredClone,AbortController,crypto:webcrypto,setTimeout,clearTimeout,require(name){if(['react','react/jsx-runtime'].includes(name))return require(name);if(name==='antd')return antd;if(name==='../course-web/WebWorkspace')return ()=>React.createElement('div',{'data-web-workspace':true});if(name==='../course-web/WebPublication')return ()=>React.createElement('div',{'data-web-publication':true});if(name==='../course-whiteboard/WhiteboardWorkspace')return ()=>React.createElement('div',{'data-whiteboard-workspace':true});if(name==='../course-animation/AnimationWorkspace')return ()=>React.createElement('div',{'data-animation-workspace':true});if(name==='@ant-design/icons')return new Proxy({},{get:()=>()=>null});if(name==='../story-comic/ComicCanvas')return (({children})=>React.createElement('div',{'data-course-canvas':true},children));if(name==='../story-comic/PrintPanel')return (({defaultNumbers})=>React.createElement('div',{'data-course-print':true},String(defaultNumbers)));if(name==='./Publication')return Object.assign(()=>React.createElement('div',{'data-course-publication':true}),{publicationPages:c=>c.plan?.pages??[]});if(name==='./store')return store;if(name==='./export')return {pngData:async x=>x,exportPage:async()=>{},exportZip:async()=>{},exportPdf:async()=>{}};if(name==='../comics/images')return {imageSource:async x=>x,referenceImage:async x=>x.src};if(name==='../story-comic/previewImages')return {previewImageSource:async x=>x};if(name==='../design-studio/images')return {storeImage:async x=>x};if(name==='../tasks/store')return {beginTask:()=>({finish(){}}),failTask(){},updateTask(){}};if(name==='../list-projects/Projects')return {useProjects:()=>({projectOf:()=>null,menu:()=>[],handle:()=>false}),ProjectSection:()=>null};if(name==='../documentLifecycle')return {registerSyncActivationBlocker:f=>{blocker=f;return()=>{};}};if(name==='../ai/client')return {trackAiExecution:async(c,p)=>p,ai:{capabilities:async()=>({text:caps,imageGenerate:caps,referenceImages:caps,maxReferences:1}),generate:async input=>{requests.push(input);return new Promise(()=>{});}}};throw Error(name);}});
 const host=document.createElement('div');document.body.append(host);const root=createRoot(host);await act(async()=>{root.render(React.createElement(module.exports.default));await drain();});
 const button=t=>[...host.querySelectorAll('button')].find(x=>x.textContent===t||x.getAttribute('aria-label')===t);
 const click=async t=>{await act(async()=>{button(t).dispatchEvent(new window.MouseEvent('click',{bubbles:true}));await drain();});};
 const input=async value=>{const node=host.querySelector('textarea');await act(async()=>{Object.getOwnPropertyDescriptor(window.HTMLTextAreaElement.prototype,'value').set.call(node,value);node.dispatchEvent(new window.Event('input',{bubbles:true}));await drain();});};
 return {host,store,docs,reads,requests,button,click,input,get creates(){return creates;},blocker:()=>blocker(),failFlush(){flushFailure=true;},holdFlush(){let resolve;flushWait=new Promise(r=>resolve=r);return()=>{flushWait=null;resolve();};},close:async()=>{await act(async()=>root.unmount());host.remove();}};
}
test('creation and examples remain drafts; disabled future modes and folding are recoverable',async()=>{const h=await harness(true);assert.equal(h.creates,0);assert.equal(h.button('白板沙画').disabled,false);await h.click('折叠导航');assert.equal(h.host.querySelector('.course-nav'),null);await h.click('展开导航');assert.ok(h.host.querySelector('.course-nav'));await act(async()=>{h.host.querySelector('.course-example').click();await drain();});assert.equal(h.host.querySelectorAll('.course-reference-image').length,5);assert.ok(h.host.querySelector('[role=dialog]'));assert.equal(h.button('复制为我的作品'),undefined);assert.equal(h.button('以此为参考创作'),undefined);await h.click('关闭预览');assert.equal(h.host.querySelector('[role=dialog]'),null);assert.equal(h.creates,0);await h.close();});
test('pointerdown without click selects once; trailing click deduplicates',async()=>{const h=await harness();const b=h.button('b');await act(async()=>{const e=new window.MouseEvent('pointerdown',{bubbles:true,button:0});Object.defineProperty(e,'pointerType',{value:'mouse'});b.dispatchEvent(e);await drain();});assert.equal(h.store.lastDocumentId,'b');assert.equal(h.reads.filter(x=>x==='b').length,1);await act(async()=>{b.dispatchEvent(new window.MouseEvent('click',{bubbles:true,detail:1}));await drain();});assert.equal(h.reads.filter(x=>x==='b').length,1);await h.close();});
test('failed save keeps current document and does not read the target',async()=>{const h=await harness();h.failFlush();await h.click('b');assert.equal(h.store.lastDocumentId,'a');assert.equal(h.reads.includes('b'),false);assert.match(h.host.textContent,/保存失败/);await h.close();});
test('IME defers navigation through final input and activation blocker protects pending save',async()=>{const h=await harness();const area=h.host.querySelector('textarea');await act(async()=>{area.dispatchEvent(new window.CompositionEvent('compositionstart',{bubbles:true}));await drain();});assert.equal(h.blocker(),true);await h.click('b');assert.equal(h.store.lastDocumentId,'a');await act(async()=>{area.dispatchEvent(new window.CompositionEvent('compositionend',{bubbles:true}));await new Promise(r=>setTimeout(r,5));await drain();});assert.equal(h.store.lastDocumentId,'b');assert.equal(h.blocker(),false);await h.close();});
test('empty topic or unsupported provider creates no record or model request',async()=>{const h=await harness(true,false);await h.click('生成知识卡片');assert.equal(h.creates,0);await h.input('解释一个知识点');await h.click('生成知识卡片');assert.equal(h.creates,0);assert.equal(h.requests.length,0);await h.close();});
test('double submit creates one durable work before model call',async()=>{const h=await harness(true);await h.input('解释一个知识点');await act(async()=>{h.button('生成知识卡片').click();h.button('生成知识卡片').click();await drain();});assert.equal(h.creates,1);assert.equal(h.requests.length,1);assert.equal(h.host.querySelector('.course-tabs [aria-current]').textContent,'知识卡片');assert.match(h.host.textContent,/正在/);assert.ok(h.docs.get('new-1').content.includes('解释一个知识点'));await h.close();});

test('reference preview preserves the current work, draft and navigation without writes',async()=>{const h=await harness();await act(async()=>{h.host.querySelector(".course-create-row").click();await drain();});await h.input("尚未生成的课程草稿");const reads=h.reads.length;await act(async()=>{h.host.querySelector(".course-example").click();await drain();});assert.equal(h.host.querySelectorAll(".course-reference-image").length,5);assert.equal(h.reads.length,reads);assert.equal(h.creates,0);assert.equal(h.host.querySelector("textarea").value,"尚未生成的课程草稿");assert.ok(h.button("下载"));await h.click("关闭预览");assert.equal(h.host.querySelector("textarea").value,"尚未生成的课程草稿");await h.close();});

test('make same fills all draft configuration without generating or creating a work',async()=>{const h=await harness(true);await h.click('做水的一次旅行同款');assert.equal(h.host.querySelector('[role=dialog]'),null);assert.match(h.host.querySelector('textarea').value,/水/);assert.equal(h.host.querySelector('select[aria-label="学习对象"]').value,'儿童');assert.equal(h.host.querySelector('select[aria-label="画面风格"]').value,'chalkboard');assert.equal(h.host.querySelector('select[aria-label="内容布局"]').value,'flow');assert.equal(h.host.querySelector('select[aria-label="主题配色"]').value,'default');assert.equal(h.host.querySelector('select[aria-label="卡片数量（含封面与结尾）"]').value,'5');assert.equal(h.host.querySelector('select[aria-label="画面比例"]').value,'3:4');assert.equal(h.creates,0);assert.equal(h.requests.length,0);await h.close();});
test('make same preserves saved work; failed save cannot replace current preferences',async()=>{const h=await harness();const before=h.docs.get('a').content;await h.click('做把大任务拆小同款');assert.equal(h.docs.get('a').content,before);assert.equal(h.host.querySelector('select[aria-label="画面风格"]').value,'sketch-notes');assert.equal(h.creates,0);await h.close();const f=await harness();f.failFlush();await f.click('做水的一次旅行同款');assert.equal(f.host.querySelector('textarea').value,config.topic);assert.equal(f.store.lastDocumentId,'a');assert.match(f.host.textContent,/保存失败/);await f.close();});

test('course result tabs expose shared publication and print panels without writes',async()=>{const h=await harness();for(const label of ['偏好','知识卡片','发布','下载','打印'])assert.ok(h.button(label));await h.click('发布');assert.ok(h.host.querySelector('[data-course-publication]'));await h.click('打印');assert.equal(h.host.querySelector('[data-course-print]').textContent,'false');await h.click('下载');assert.ok(h.button('下载封面'));assert.ok(h.button('下载全部 · ZIP'));assert.ok(h.button('下载 PDF'));assert.equal(h.creates,0);assert.equal(h.requests.length,0);await h.close();});

test('animation creation is a draft and exposes tutorial tabs without model calls or files',async()=>{const h=await harness(true);assert.equal(h.button('动画教程').disabled,false);await h.click('动画教程');assert.ok(h.host.querySelector('[data-animation-workspace]'));for(const t of ['偏好','动画','脚本','发布','下载'])assert.ok(h.button(t));await h.click('发布');assert.ok(h.host.querySelector('[data-course-publication]'));assert.equal(h.creates,0);assert.equal(h.requests.length,0);await h.close();});

test('whiteboard creation opens a draft with four product tabs and creates no file',async()=>{const h=await harness();await h.click('白板沙画');assert.ok(h.host.querySelector('[data-whiteboard-workspace]'));assert.equal(h.creates,0);assert.equal(h.requests.length,0);await h.close();});

test('interactive web creation opens its three tabs without making a local document',async()=>{const h=await harness(true);await h.click('交互网页');assert.ok(h.host.querySelector('[data-web-workspace]'));assert.ok(h.button('作品'));assert.ok(h.button('发布'));assert.equal(h.button('下载'),undefined);assert.equal(h.creates,0);await h.click('发布');assert.ok(h.host.querySelector('[data-web-publication]'));await h.close();});
