import {test} from 'node:test';import assert from 'node:assert/strict';import {buildSync} from 'esbuild';import vm from 'node:vm';import fs from 'node:fs';
const module={exports:{}};vm.runInNewContext(buildSync({entryPoints:['src/course-whiteboard/workflow.ts'],bundle:true,write:false,format:'cjs',platform:'node'}).outputFiles[0].text,{module,structuredClone});const {runWorkflow}=module.exports;const modelModule={exports:{}};vm.runInNewContext(buildSync({entryPoints:['src/course-whiteboard/model.ts'],bundle:true,write:false,format:'cjs',platform:'node'}).outputFiles[0].text,{module:modelModule});const {eventCaptions}=modelModule.exports;const r=JSON.parse(fs.readFileSync('scripts/course-whiteboard/reference-content.json'))[0];const input={topic:r.title,config:r.config};
function harness(){const calls=[],saves=[];let current=true,images=0,check=0;return {calls,saves,get images(){return images;},invalidate(){current=false;},deps:{valid:()=>current,text:async()=>{calls.push('text');return JSON.stringify({...r,summary:r.title});},prepare:async p=>{calls.push('srt-audio');return {...p,scenes:p.scenes.map(s=>({...s,audio:'workstore-course-media:'+ 'b'.repeat(64)+'.wav',audioVoice:'kokoro-zh-zf_021-s0.93-v1',captions:eventCaptions(s)}))};},image:async()=>{calls.push('image');images++;return 'workstore-image:'+'a'.repeat(64);},dimensions:async()=>({width:1672,height:941}),inspect:async()=>{calls.push('vision');return JSON.stringify({ok:true,reason:'四个实际主体对应字幕事件',subjects:r.scenes[0].events.map(e=>e.subject)});},render:async()=>{calls.push('render');return 'workstore-course-media:'+'c'.repeat(64)+'.mp4';},save:async(c,stage)=>{calls.push('save');saves.push({c,stage});}}};}
test('topic automatically becomes durable script and SRT before image inspection, masks and real rendering',async()=>{const h=harness();const result=await runWorkflow(input,h.deps,new AbortController().signal,'original skill rules');assert.equal(h.saves[0].c.prompt.includes(input.topic),true);assert.ok(h.saves.find(s=>s.stage.includes('SRT已保存')).c.plan.srt);assert.ok(h.calls.indexOf('srt-audio')<h.calls.indexOf('image'));assert.ok(h.calls.indexOf('vision')<h.calls.indexOf('render'));assert.equal(result.plan.scenes[0].annotation.elements.length,4);assert.match(result.plan.video,/workstore-course-media:/);});
test('failed actual image inspection exhausts four automatic attempts then refuses invalid images',async()=>{const h=harness();h.deps.inspect=async()=>JSON.stringify({ok:false,reason:'源图含文字',subjects:['一','二','三','四']});await assert.rejects(()=>runWorkflow(input,h.deps,new AbortController().signal,'skill'),/自动校验失败/);assert.equal(h.images,4);assert.equal(h.calls.includes('render'),false);assert.ok(h.saves.at(-1).c.plan.srt);});
test('editing during a pending model call never overwrites changed content',async()=>{const h=harness();h.deps.text=async()=>{h.invalidate();return JSON.stringify({...r,summary:r.title});};await assert.rejects(()=>runWorkflow(input,h.deps,new AbortController().signal,'skill'));assert.equal(h.saves.length,1);assert.equal(h.images,0);});
test('resume reuses complete checked scenes and prepared voice without model or image calls',async()=>{const first=harness();const result=await runWorkflow(input,first.deps,new AbortController().signal,'skill');const h=harness();await runWorkflow(result,h.deps,new AbortController().signal,'skill');assert.equal(h.images,0);assert.equal(h.calls.includes('text'),false);assert.equal(h.calls.includes('srt-audio'),false);assert.equal(h.calls.includes('render'),true);});
test('invalid actual image dimensions automatically regenerate instead of asking for annotation input',async()=>{const h=harness();let attempts=0;h.deps.dimensions=async()=>{if(!attempts++)throw Error('源图不是16:9');return {width:1672,height:941};};const result=await runWorkflow(input,h.deps,new AbortController().signal,'skill');assert.equal(h.images,2);assert.ok(result.plan.video);});

test('a changed topic rebuilds the cached planning prompt before retrying a failed script stage',async()=>{const h=harness();const result=await runWorkflow({...input,topic:'新的教学主题',prompt:'旧主题的提示词'},h.deps,new AbortController().signal,'skill');assert.ok(h.saves[0].c.prompt.includes('新的教学主题'));assert.ok(!h.saves[0].c.prompt.includes('旧主题的提示词'));assert.ok(result.plan.video);});

test('an automatic correction switches colored subjects to gray and succeeds without intervention',async()=>{const h=harness();let checks=0;const prompts=[];h.deps.image=async prompt=>{prompts.push(prompt);return 'workstore-image:'+'a'.repeat(64);};h.deps.inspect=async()=>JSON.stringify({ok:!!checks++,reason:checks===1?'光束含黄色':'灰色线稿通过',subjects:['一','二','三','四']});const result=await runWorkflow({...input,config:{...input.config,style:undefined}},h.deps,new AbortController().signal,'skill');assert.equal(prompts.length,2);assert.match(prompts[1],/纯灰色铅笔线稿/);assert.ok(result.plan.video);});

test('an interrupted image service retries automatically and preserves prepared script and audio',async()=>{const h=harness();let attempts=0;h.deps.image=async()=>{if(!attempts++)throw Error('Codex 未完成请求');return 'workstore-image:'+'a'.repeat(64);};const result=await runWorkflow(input,h.deps,new AbortController().signal,'skill');assert.equal(attempts,2);assert.ok(h.saves.some(s=>s.stage.includes('自动重试')));assert.ok(result.plan.video);assert.ok(result.plan.scenes[0].audio);});

test('changing narration voice reuses inspected images and re-times annotations without rewriting content',async()=>{const first=harness(),ready=await runWorkflow(input,first.deps,new AbortController().signal,'skill');const h=harness();const result=await runWorkflow({...ready,config:{...ready.config,voiceId:'zf_018'}},h.deps,new AbortController().signal,'skill');assert.ok(h.calls.includes('srt-audio'));assert.equal(h.calls.includes('text'),false);assert.equal(h.images,0);assert.ok(result.plan.scenes[0].annotation);});

test('style corrections retain the selected medium through planning, generation and inspection',async()=>{const h=harness(),prompts=[],inspections=[];let checks=0;h.deps.image=async prompt=>{prompts.push(prompt);return 'workstore-image:'+'a'.repeat(64);};h.deps.inspect=async(prompt,_image)=>{inspections.push(prompt);return JSON.stringify({ok:!!checks++,reason:'分区图形检查',subjects:['一','二','三','四']});};await runWorkflow({...input,config:{...input.config,style:'watercolor'}},h.deps,new AbortController().signal,'default warm skill');assert.match(h.saves[0].c.prompt,/透明水彩/);assert.equal(prompts.length,2);for(const prompt of [...prompts,...inspections]){assert.match(prompt,/透明水彩/);assert.doesNotMatch(prompt,/纯灰色铅笔线稿|不得用绿色/);}});
