import {test} from 'node:test';
import assert from 'node:assert/strict';
import {buildSync} from 'esbuild';
import {createRequire} from 'node:module';
import vm from 'node:vm';
import {webcrypto} from 'node:crypto';
const require=createRequire(import.meta.url);
function bundle(file,external=[]){return buildSync({entryPoints:[file],bundle:true,write:false,platform:'node',format:'cjs',external}).outputFiles[0].text;}
function evaluate(code,mocks={}){const module={exports:{}};vm.runInNewContext(code,{module,exports:module.exports,require:id=>id in mocks?mocks[id]:require(id),crypto:webcrypto,structuredClone,AbortController,console});return module.exports;}
const m=evaluate(bundle('src/design-studio/canvas/model.ts'));
const image=n=>'workstore-image:'+String(n).repeat(64);
const plain=x=>JSON.parse(JSON.stringify(x));
test('canvas content round-trips separately from feature documents and rejects corrupt graph data',()=>{const c=m.blankCanvas();assert.equal(m.isCanvas(JSON.stringify(c)),true);assert.equal(m.isCanvas(JSON.stringify({featureId:'0-0'})),false);assert.deepEqual(plain(m.readCanvas(JSON.stringify(c))),plain(c));const broken=structuredClone(c);broken.edges=[{id:'bad',source:'missing',target:c.nodes[0].id}];assert.throws(()=>m.readCanvas(JSON.stringify(broken)),/连线/);broken.edges=[];broken.nodes[0].data.params.count=100;assert.throws(()=>m.readCanvas(JSON.stringify(broken)),/参数/);});
test('only images can be connected as input, connections deduplicate and reference count is limited to five',()=>{let c=m.blankCanvas();const p=c.nodes[0];for(let i=1;i<=6;i++)c.nodes.push(m.imageNode({x:0,y:i*20},[image(i)]));assert.throws(()=>m.connectInput(c,p.id,c.nodes[1].id),/图片节点/);for(const n of c.nodes.slice(1,6))c=m.connectInput(c,n.id,p.id);assert.equal(c.edges.length,5);assert.equal(m.connectInput(c,c.nodes[1].id,p.id).edges.length,5);assert.throws(()=>m.connectInput(c,c.nodes[6].id,p.id),/5张/);p.data.prompt='场景融合';const snap=m.submission(c,p.id);assert.equal(snap.references.length,5);c.nodes[1].data.images=[image(7)];assert.equal(snap.references[0],image(1));});
test('multi-image branches preserve existing graph and node deletion removes its dependent edges',()=>{const c=m.blankCanvas();const a=m.imageNode({x:0,y:100},[image(1)]),b=m.imageNode({x:200,y:100},[image(2)]);c.nodes.push(a,b);const branch=m.newBranch(c,[a.id,b.id]);assert.equal(c.nodes.length,3);assert.equal(branch.canvas.nodes.length,4);assert.equal(m.referenceNodes(branch.canvas,branch.id).length,2);const next=m.removeNodes(branch.canvas,[a.id]);assert.equal(next.edges.length,1);assert.equal(next.nodes.length,3);});
test('result callbacks preserve edits and refuse deleted or replaced output nodes',()=>{const c=m.blankCanvas(),n=m.imageNode({x:400,y:0},[],{runId:'one',status:'generating'});c.nodes.push(n);c.nodes[0].data.prompt='下一次提示词';const result=m.finishNode(c,n.id,'one',{images:[image(1)],status:'ready'});assert.equal(result.nodes[0].data.prompt,'下一次提示词');assert.throws(()=>m.finishNode(result,n.id,'other',{}),/已变化/);assert.throws(()=>m.finishNode({...c,deletedAt:1},n.id,'one',{}),/已变化/);});
function harness(){
 let c=m.blankCanvas();c.nodes[0].data.prompt='原始提示词';c.nodes[0].data.params.count=2;
 const document={id:'canvas',title:'测试画布',content:JSON.stringify(c)},calls=[],pending=[];let version=0,failed=false;
 const store={currentDocument:()=>document,remoteVersion:()=>version,stageDocument:(_,patch)=>Object.assign(document,patch),flushDocument:async()=>{if(failed)throw Error('磁盘保存失败');}};
 const ai={capabilities:async()=>({imageGenerate:true,referenceImages:true,maxReferences:8}),generate:async(request,signal)=>{calls.push(request);return new Promise((resolve,reject)=>{pending.push({resolve,reject});signal.addEventListener('abort',()=>reject(Error('停止')),{once:true});});}};
 const e=evaluate(bundle('src/design-studio/canvas/execution.ts',['../store','../images','../../ai/client','../../tasks/store']),{'../store':store,'../images':{reference:async x=>x},'../../ai/client':{ai,trackAiExecution:(_,promise)=>promise},'../../tasks/store':{beginTask:()=>({finish(){}}),updateTask(){}}});
 return{e,document,calls,node:c.nodes[0].id,read:()=>m.readCanvas(document.content),sync:()=>version++,failSave:()=>failed=true,answer:(n,result)=>pending[n].resolve(result),tick:()=>new Promise(resolve=>setImmediate(resolve))};
}
test('canvas generation stores all candidates, preserves newer prompt edits and regenerates from submitted snapshot',async()=>{const h=harness();const task=h.e.generateNode('canvas',h.node);await h.tick();assert.equal(h.calls.length,1);let c=h.read();assert.equal(c.nodes.length,2);assert.equal(c.nodes[1].data.status,'generating');c.nodes[0].data.prompt='新输入';h.document.content=JSON.stringify(c);h.answer(0,{images:[image(1)],text:''});await h.tick();assert.equal(h.calls.length,2);h.answer(1,{images:[image(2)],text:''});await task;c=h.read();assert.equal(c.nodes[0].data.prompt,'新输入');assert.deepEqual(plain(c.nodes[1].data.images),[image(1),image(2)]);const output=c.nodes[1].id;const retry=h.e.generateNode('canvas',output,true);await h.tick();assert(h.calls[2].messages[0].content.includes('原始提示词'));assert(!h.calls[2].messages[0].content.includes('新输入'));h.answer(2,{images:[image(3)],text:''});await h.tick();h.answer(3,{images:[image(4)],text:''});await retry;assert.equal(h.read().nodes[1].data.images.length,4);});
test('cancelling a batch retains completed candidates and prevents late model callbacks from replacing synchronized data',async()=>{const h=harness();const task=h.e.generateNode('canvas',h.node);const settled=task.catch(e=>String(e));await h.tick();h.answer(0,{images:[image(1)],text:''});await h.tick();h.e.stopNode('canvas',h.node);await settled;assert.equal(h.read().nodes[1].data.status,'cancelled');assert.equal(h.read().nodes[1].data.images.length,1);const next=harness();const run=next.e.generateNode('canvas',next.node).catch(e=>String(e));await next.tick();next.sync();const before=next.document.content;next.answer(0,{images:[image(2)],text:''});assert((await run).includes('同步'));assert.equal(next.document.content,before);});
test('failed canvas persistence blocks model execution and leaves a retryable output node',async()=>{const h=harness();h.failSave();await assert.rejects(h.e.generateNode('canvas',h.node),/保存失败/);assert.equal(h.calls.length,0);assert.equal(h.read().nodes[1].data.status,'error');});


test('image editing branches avoid an existing prompt at the default position',()=>{const c=m.blankCanvas();const im=m.imageNode({x:-280,y:100},[image(1)]);c.nodes.push(im);const branch=m.newBranch(c,[im.id]);const added=branch.canvas.nodes.find(n=>n.id===branch.id);assert.notDeepEqual(added.position,c.nodes[0].position);assert.equal(m.referenceNodes(branch.canvas,branch.id).length,1);});
