import CourseCoverPanel from '../course/CourseCoverPanel';
import {useEffect,useState} from 'react';import {Button,Card,Input,Modal,App} from 'antd';import {openUrl} from '@tauri-apps/plugin-opener';import * as store from '../course/store';import type {Content} from '../course/model';import {publishApi,type PublishConfig,type PublishResult} from './publish';import {exportHtmlFile} from '../html/export';import WebPreview from './Preview';
export default function WebPublication({id,content,disabled,onCover,onError}:{id:string|null;content?:Content;disabled:boolean;onCover?:(style?:string,instruction?:string)=>void;onError:(e:unknown)=>void}){const {modal,message}=App.useApp(),[config,setConfig]=useState<PublishConfig|null>(null),[settings,setSettings]=useState(false),[token,setToken]=useState(''),[team,setTeam]=useState(''),[loading,setLoading]=useState(false),[preview,setPreview]=useState(false),[result,setResult]=useState<PublishResult|null>(null);const plan=content?.webPlan;
 useEffect(()=>{let live=true;setResult(null);void publishApi<PublishConfig>('config').then(c=>{if(live){setConfig(c);setTeam(c.teamId??'');}}).catch(()=>{if(live)setConfig(null);});return()=>{live=false;};},[id,!!plan]);
 const act=(p:Promise<unknown>)=>void p.catch(onError);
 async function saveConfig(){if(!token.trim()&&!config?.configured)throw Error('请先输入 Vercel Token');setLoading(true);try{const next=await publishApi<PublishConfig>('save-config',{token:token.trim()||config?.tokenMask||'',teamId:team.trim()});setConfig(next);setToken('');setSettings(false);}finally{setLoading(false);}}
 async function publish(){if(!id||!plan||loading)return;const target=id,original=store.currentDocument(id)!.content,remote=store.remoteVersion(id),html=plan.html;setLoading(true);try{const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(html)))).map(b=>b.toString(16).padStart(2,'0')).join('');const value=await publishApi<PublishResult>('publish',{taskId:target,html});setResult(value);if(store.remoteVersion(target)===remote&&store.currentDocument(target)?.content===original){const c=JSON.parse(original) as Content;c.webDeployments=[{...value,id:crypto.randomUUID(),hash,createdAt:Date.now()},...(c.webDeployments??[])].slice(0,5);store.stageDocument(target,{content:JSON.stringify(c)});await store.flushDocument(target);}else message.info('网页已发布；作品期间有修改，发布记录未覆盖新内容。');}finally{setLoading(false);}}
 const confirm=()=>modal.confirm({title:'发布此交互网页？',content:'当前页面将上传到你的 Vercel 账户，并生成可访问链接。平台访问保护由现有配置决定。',okText:'发布网页',cancelText:'取消',onOk:()=>publish().catch(onError)});
 return <div className="course-web-publication">{content&&onCover&&<CourseCoverPanel content={content} disabled={disabled} onGenerate={onCover} onError={onError}/>}<Card title="在线发布" extra={<><Button size="small" disabled={!plan||disabled||loading} onClick={()=>setPreview(true)}>预览</Button> <Button size="small" onClick={()=>setSettings(true)}>发布配置</Button> <Button size="small" type="primary" loading={loading} disabled={!plan||!config?.configured||disabled} onClick={confirm}>发布到 Vercel</Button></>}><h3>{plan?.title??'先制作交互网页'}</h3><p>{plan?.summary??'制作完成后，可发布网页供他人直接操作体验。'}</p><p className="course-web-muted">{config?.configured?'已连接 HTML 工具的 Vercel 发布配置':'尚未连接发布配置，填写后即可发布。'}</p>{result&&<div role="status"><p>{result.statusMessage}</p><Button size="small" onClick={()=>act(openUrl(result.url))}>打开网页</Button> <Button size="small" onClick={()=>act(navigator.clipboard.writeText(result.url))}>复制链接</Button><p>{result.url}</p></div>}</Card><Card title="发布记录" extra={<Button size="small" disabled={!plan||disabled} onClick={()=>plan&&act(exportHtmlFile(plan.title,plan.html))}>下载 HTML</Button>}>{content?.webDeployments?.length?content.webDeployments.map(d=><div className="course-web-deployment" key={d.id}><span>{new Date(d.createdAt).toLocaleString()} · {d.statusMessage}</span><Button size="small" onClick={()=>act(openUrl(d.url))}>打开</Button><code>{d.url}</code><small>{d.hash.slice(0,12)}</small></div>):<p>暂无发布记录。也可下载单文件 HTML，自行托管。</p>}</Card><Modal title="发布配置" open={settings} okText="保存配置" cancelText="取消" confirmLoading={loading} onCancel={()=>{setSettings(false);setToken('');}} onOk={()=>act(saveConfig())}><p>与 HTML 工具共用设备上的 Vercel 配置。凭据只保存在本机。</p><label>Vercel Token<Input.Password autoComplete="off" aria-label="Vercel Token" value={token} placeholder={config?.configured?'已保存，留空保持现有凭据':'输入 Vercel Token'} onChange={e=>setToken(e.target.value)}/></label><label>团队 ID（可选）<Input aria-label="Vercel 团队 ID" value={team} onChange={e=>setTeam(e.target.value)}/></label></Modal><Modal title={plan?.title} open={preview} width="95vw" footer={null} destroyOnHidden onCancel={()=>setPreview(false)}>{plan&&<WebPreview html={plan.html} title={plan.title}/>}</Modal></div>;
}
