import {readFile,writeFile,mkdir,cp,rm} from 'node:fs/promises';
import {createHash} from 'node:crypto';import {spawnSync} from 'node:child_process';import {build} from 'esbuild';import path from 'node:path';
const install=spawnSync(process.execPath,['scripts/course-whiteboard/install-runtime.mjs'],{stdio:'inherit'});if(install.status)throw Error('Whiteboard Python preparation failed');
const speech=spawnSync(process.execPath,['scripts/ai/install-speech.mjs'],{stdio:'inherit'});if(speech.status)throw Error('Natural speech preparation failed');
const root=process.cwd(),out=path.join(root,'src-tauri/whiteboard-runtime'),stage=path.join(root,'.course-whiteboard-build/runtime'),python=path.join(root,'.course-whiteboard-build/python');
const upstream=JSON.parse(await readFile('vendor/srt-whiteboard-animation/UPSTREAM.json','utf8'));for(const [name,expected]of Object.entries(upstream.sha256)){if(createHash('sha256').update(await readFile('vendor/srt-whiteboard-animation/'+name)).digest('hex')!==expected)throw Error('Whiteboard skill source changed: '+name);}
const font=JSON.parse(await readFile('vendor/course-whiteboard-font/UPSTREAM.json','utf8'));for(const[name,expected]of Object.entries(font.files)){if(createHash('sha256').update(await readFile('vendor/course-whiteboard-font/'+name)).digest('hex')!==expected)throw Error('Whiteboard font source changed: '+name);}
const h=createHash('sha256');for(const f of ['scripts/course-whiteboard/build-runtime.mjs','scripts/course-whiteboard/render.py','scripts/course-whiteboard/analyze.py','scripts/ai/speech.py','scripts/ai/speech-requirements.txt','vendor/course-tts/UPSTREAM.json','src/course-whiteboard/assets/drawing-hand.png','vendor/course-whiteboard-font/UPSTREAM.json','.course-whiteboard-build/python-source.json','src/course-whiteboard/model.ts','src/course-whiteboard/styles.ts','src/course-animation/model.ts','src/course-animation/styles.ts','vendor/srt-whiteboard-animation/UPSTREAM.json'])h.update(await readFile(f));h.update(process.platform+process.arch);const buildId=h.digest('hex').slice(0,24);
try{const m=JSON.parse(await readFile(path.join(out,'manifest.json'),'utf8'));if(m.buildId===buildId){await readFile(path.join(out,'app.tar.gz'));console.log('Whiteboard runtime is up to date.');process.exit(0);}}catch{}
await rm(stage,{recursive:true,force:true});await mkdir(stage,{recursive:true});await mkdir(out,{recursive:true});
await cp(python,path.join(stage,'python'),{recursive:true,verbatimSymlinks:true});await cp('vendor/srt-whiteboard-animation',path.join(stage,'skill'),{recursive:true,verbatimSymlinks:true,filter:s=>!s.includes('/.venv')&&!s.includes('__pycache__')});
await cp('.course-tts-build/models',path.join(stage,'speech'),{recursive:true,verbatimSymlinks:true,filter:s=>!s.endsWith('README.md')});await cp('scripts/ai/speech.py',path.join(stage,'speech/speech.py'));await cp('vendor/course-tts',path.join(stage,'speech/licenses'),{recursive:true,verbatimSymlinks:true});
for(const[source,target]of [['scripts/course-whiteboard/render.py','render.py'],['scripts/course-whiteboard/analyze.py','analyze.py'],['src/course-whiteboard/assets/drawing-hand.png','drawing-hand.png'],['vendor/course-whiteboard-font/NotoSansCJKsc-Regular.otf','font.ttf'],['vendor/course-whiteboard-font/LICENSE','font-license.txt']])await cp(source,path.join(stage,target));
await build({entryPoints:['src/course-whiteboard/model.ts'],bundle:true,platform:'node',format:'cjs',outfile:path.join(stage,'model.cjs')});
const tar=spawnSync('tar',['-czf',path.join(out,'app.tar.gz'),'-C',stage,'.'],{stdio:'inherit'});if(tar.status)throw Error('Whiteboard runtime packaging failed');await writeFile(path.join(out,'manifest.json'),JSON.stringify({buildId,commit:upstream.commit,platform:process.platform,arch:process.arch},null,2));console.log('Whiteboard runtime built:',buildId);
