import {readFile,writeFile,access,copyFile,rm} from 'node:fs/promises';import {spawn,spawnSync} from 'node:child_process';import path from 'node:path';import {createRequire} from 'node:module';import {build} from 'esbuild';
const root=process.cwd();await build({entryPoints:['src/course-whiteboard/model.ts'],bundle:true,platform:'node',format:'cjs',outfile:'.course-whiteboard-build/reference-model.cjs'});const require=createRequire(import.meta.url),model=require(path.join(root,'.course-whiteboard-build/reference-model.cjs'));const refs=JSON.parse(await readFile('scripts/course-whiteboard/reference-content.json','utf8'));
const nodeRun=path.join(root,'.course-animation-build/runtime'),pythonRun=path.join(root,'.course-whiteboard-build/runtime');
function run(stage,job){return new Promise((resolve,reject)=>{const p=spawn(process.execPath,[path.join(nodeRun,'runner.mjs'),stage,job],{env:{...process.env,WORKSTORE_WHITEBOARD:pythonRun},stdio:['ignore','pipe','pipe']});let err='';p.stdout.on('data',b=>{for(const l of String(b).split('\n'))try{const v=JSON.parse(l);if(v.progress===1)console.log(path.basename(job),v.stage);}catch{}});p.stderr.on('data',b=>{err+=b;});p.on('exit',c=>c===0?resolve():reject(Error(err)));p.on('error',reject);});}
const meta=[];
async function renderReference(r){const job=path.join(root,'public/course/whiteboard',r.id);for(let i=0;i<r.scenes.length;i++){const png=path.join(job,String(i+1).padStart(2,'0')+'.png');for(;;){try{await access(png);break;}catch{await new Promise(resolve=>setTimeout(resolve,3000));}}}
 for(;;){try{await access(path.join(job,'.reviewed'));break;}catch{await new Promise(resolve=>setTimeout(resolve,3000));}}
 let plan=model.parsePlan(JSON.stringify({title:r.title,summary:r.scenes.map(s=>s.title).join('；'),scenes:r.scenes}),r.config);plan.scenes.forEach((s,i)=>{s.image=`/course/whiteboard/${r.id}/${String(i+1).padStart(2,'0')}.png`;s.imagePrompt=model.imagePrompt(s);});await writeFile(path.join(job,'input.json'),JSON.stringify({tutorial:plan,config:r.config}));console.log('PREPARE',r.id);
 await run('whiteboard-prepare',job);plan=JSON.parse(await readFile(path.join(job,'result.json'),'utf8'));
 for(let i=0;i<plan.scenes.length;i++){const s=plan.scenes[i],name=String(i+1).padStart(2,'0');const b=await readFile(path.join(job,name+'.png'));const width=b.readUInt32BE(16),height=b.readUInt32BE(20);const measure=spawnSync(path.join(pythonRun,'python/bin/python3'),[path.join(pythonRun,'analyze.py'),path.join(job,name+'.png')],{encoding:'utf8',env:{...process.env,PYTHONHOME:path.join(pythonRun,'python'),PYTHONNOUSERSITE:'1'}});if(measure.status)throw Error(measure.stderr);const measured=JSON.parse(measure.stdout);s.annotation=model.annotate(s,i,width,height,measured.regions);s.inspection='已实际查看源图，四个独立象限与字幕事件对应，无源图文字、交叠或跨区主体。';if(s.audio)s.audio=`/course/whiteboard/${r.id}/${name}.wav`;await writeFile(path.join(job,name+'.annotation.json'),JSON.stringify(s.annotation,null,2));await writeFile(path.join(job,name+'-prompt.md'),s.imagePrompt);}
 model.validatePlan(plan,r.config);await writeFile(path.join(job,'input.json'),JSON.stringify({tutorial:plan,config:r.config}));console.log('RENDER',r.id);await run('whiteboard-render',job);plan.video=`/course/whiteboard/${r.id}/tutorial.mp4`;await writeFile(path.join(job,'tutorial.json'),JSON.stringify(plan,null,2));await copyFile(path.join(job,'01.png'),path.join(job,'cover.png'));meta.push({id:r.id,title:r.title,topic:r.topic,config:r.config,cover:`/course/whiteboard/${r.id}/cover.png`,video:plan.video,scenes:plan.scenes.length});meta.sort((a,b)=>refs.findIndex(r=>r.id===a.id)-refs.findIndex(r=>r.id===b.id));await writeFile('src/course-whiteboard/examples.json',JSON.stringify(meta,null,2));console.log('COMPLETE',r.id);
 for(let i=0;i<plan.scenes.length;i++){const n=String(i+1).padStart(2,'0');for(const suffix of ['-raw.wav','.txt','-draw.mp4'])await rm(path.join(job,n+suffix),{force:true});}for(const f of ['merged.mp4','audio.txt','rendered.json','result.json','input.json'])await rm(path.join(job,f),{force:true});
}
let cursor=0;await Promise.all(Array.from({length:3},async()=>{while(cursor<refs.length)await renderReference(refs[cursor++]);}));console.log('All ten whiteboard tutorials rendered.');
