import {readFile,writeFile,mkdir,cp,rm} from 'node:fs/promises';
import {spawn} from 'node:child_process';import path from 'node:path';import {createRequire} from 'node:module';
const runtime=path.resolve('.course-animation-build/runtime'),speech=path.resolve('.course-whiteboard-build/runtime'),require=createRequire(import.meta.url),model=require(path.join(runtime,'whiteboard-model.cjs'));
const refs=JSON.parse(await readFile('src/course-whiteboard/examples.json','utf8'));
function run(stage,job){return new Promise((resolve,reject)=>{const child=spawn(process.execPath,[path.join(runtime,'runner.mjs'),stage,job],{env:{...process.env,WORKSTORE_WHITEBOARD:speech},stdio:['ignore','pipe','pipe']});let err='';child.stdout.on('data',b=>{for(const l of String(b).split('\n'))try{const p=JSON.parse(l);if(p.progress===1)console.log(path.basename(job),p.stage);}catch{}});child.stderr.on('data',b=>err+=b);child.on('error',reject);child.on('exit',c=>c?reject(Error(err)):resolve());});}
let cursor=0;await Promise.all(Array.from({length:2},async()=>{while(cursor<refs.length){const r=refs[cursor++],job=path.resolve('public/course/whiteboard',r.id),backup=path.resolve('.course-tts-build/whiteboard-prior-voices',r.id);await mkdir(path.dirname(backup),{recursive:true});try{await readFile(path.join(backup,'tutorial.json'));}catch{await cp(job,backup,{recursive:true});}
const old=JSON.parse(await readFile(path.join(job,'tutorial.json'),'utf8'));if(old.scenes.every(s=>s.audioVoice==='kokoro-zh-zf_021-s0.93-v1')){console.log('READY',r.id);continue;}r.config.voiceId='zf_021';await writeFile(path.join(job,'input.json'),JSON.stringify({tutorial:old,config:r.config}));await run('whiteboard-prepare',job);let plan=JSON.parse(await readFile(path.join(job,'result.json'),'utf8'));
plan.scenes.forEach((s,i)=>{s.audio=`/course/whiteboard/${r.id}/${String(i+1).padStart(2,'0')}.wav`;const a=s.annotation;s.annotation=model.annotate(s,i,a.canvas.width,a.canvas.height,a.elements.map(e=>e.region));});await writeFile(path.join(job,'input.json'),JSON.stringify({tutorial:plan,config:r.config}));await run('whiteboard-render',job);plan.video=r.video;plan.scenes.forEach((s,i)=>s.audio=`/course/whiteboard/${r.id}/${String(i+1).padStart(2,'0')}.wav`);await writeFile(path.join(job,'tutorial.json'),JSON.stringify(plan,null,2));for(let i=0;i<plan.scenes.length;i++){const n=String(i+1).padStart(2,'0');await writeFile(path.join(job,n+'.annotation.json'),JSON.stringify(plan.scenes[i].annotation,null,2));for(const suffix of ['-raw.wav','-draw.mp4'])await rm(path.join(job,n+suffix),{force:true});}for(const f of ['merged.mp4','audio.txt','rendered.json','result.json','input.json','speech-input.json','speech-result.json','speech-settings.json'])await rm(path.join(job,f),{force:true});console.log('COMPLETE',r.id);
}}));console.log('All ten whiteboard references revoiced.');
