import {readFile,writeFile,rm} from 'node:fs/promises';
import {spawn,spawnSync} from 'node:child_process';import path from 'node:path';import {createRequire} from 'node:module';import {build} from 'esbuild';
const runtime=path.resolve('.course-animation-build/runtime'),python=path.resolve('.course-whiteboard-build/runtime');
await build({entryPoints:['src/course-whiteboard/model.ts'],bundle:true,platform:'node',format:'cjs',outfile:path.join(runtime,'whiteboard-model.cjs')});
const model=createRequire(import.meta.url)(path.join(runtime,'whiteboard-model.cjs'));
const refs=JSON.parse(await readFile('src/course-whiteboard/examples.json','utf8'));const ids=process.argv.slice(2),selected=ids.length?refs.filter(r=>ids.includes(r.id)):refs;
function run(job){return new Promise((resolve,reject)=>{const child=spawn(process.execPath,[path.join(runtime,'runner.mjs'),'whiteboard-render',job],{env:{...process.env,WORKSTORE_WHITEBOARD:python},stdio:['ignore','pipe','pipe']});let err='';child.stdout.on('data',b=>process.stdout.write(b));child.stderr.on('data',b=>err+=b);child.on('error',reject);child.on('exit',c=>c?reject(Error(err)):resolve());});}
let cursor=0;await Promise.all(Array.from({length:2},async()=>{while(cursor<selected.length){const r=selected[cursor++],job=path.resolve('public/course/whiteboard',r.id);const p=JSON.parse(await readFile(path.join(job,'tutorial.json'),'utf8'));
for(let i=0;i<p.scenes.length;i++){const s=p.scenes[i],name=String(i+1).padStart(2,'0'),file=path.join(job,name+'.png');const measured=spawnSync(path.join(python,'python/bin/python3'),[path.join(python,'analyze.py'),file],{encoding:'utf8',env:{...process.env,PYTHONHOME:path.join(python,'python'),PYTHONNOUSERSITE:'1'}});if(measured.status)throw Error(r.id+': '+measured.stderr);const dimensions=JSON.parse(measured.stdout);s.annotation=model.annotate(s,i,dimensions.width,dimensions.height,dimensions.regions);s.imagePrompt=model.imagePrompt(s,r.config);s.inspection='已实际查看新风格源图，四个主体与教学事件对应，按实测像素区域与原字幕时序绘制';await writeFile(path.join(job,name+'.annotation.json'),JSON.stringify(s.annotation,null,2));await writeFile(path.join(job,name+'-prompt.md'),s.imagePrompt);}
model.validatePlan(p,r.config);await writeFile(path.join(job,'input.json'),JSON.stringify({tutorial:p,config:r.config}));console.log('RENDER STYLE',r.id,r.config.style);await run(job);p.referenceStyle=r.config.style;await writeFile(path.join(job,'tutorial.json'),JSON.stringify(p,null,2));await writeFile(path.join(job,'style.json'),JSON.stringify({style:r.config.style,cover:r.cover,ratio:'1:1'},null,2));for(let i=0;i<p.scenes.length;i++)await rm(path.join(job,String(i+1).padStart(2,'0')+'-draw.mp4'),{force:true});for(const f of ['merged.mp4','audio.txt','rendered.json','result.json','input.json'])await rm(path.join(job,f),{force:true});console.log('COMPLETE STYLE',r.id);
}}));
