import {readFile,writeFile,copyFile} from 'node:fs/promises';import path from 'node:path';import {spawn} from 'node:child_process';import {createRequire} from 'node:module';import {fileURLToPath} from 'node:url';import {RenderInternals} from '@remotion/renderer';
const require=createRequire(import.meta.url),here=path.dirname(fileURLToPath(import.meta.url));
const {selectedVoice,voiceProfile}=require('./model.cjs');
const {parsePlan,validatePlan,validateConfig,eventCaptions,toSrt}=require('./whiteboard-model.cjs');const [stage,job]=process.argv.slice(2),input=JSON.parse(await readFile(path.join(job,'input.json'),'utf8'));validateConfig(input.config);validatePlan(input.tutorial,input.config);let p=structuredClone(input.tutorial),run=process.env.WORKSTORE_WHITEBOARD;if(!run)throw Error('白板沙画渲染组件缺失');
const report=(progress,stage)=>process.stdout.write(JSON.stringify({progress,stage})+'\n');
const ff=(bin,args)=>RenderInternals.callFf({bin,args,indent:false,logLevel:'error',binariesDirectory:null,cancelSignal:undefined});
async function child(bin,args,options={}){return new Promise((resolve,reject)=>{let output='',err='';const c=spawn(bin,args,{stdio:['ignore','pipe','pipe'],...options});c.stdout.on('data',b=>{output+=b;for(const line of String(b).split('\n'))try{const v=JSON.parse(line);if(v.progress!==undefined)process.stdout.write(line+'\n');}catch{}});c.stderr.on('data',b=>{if(err.length<3000)err+=b;});c.on('error',reject);c.on('exit',code=>code===0?resolve(output):reject(Error(err||'白板沙画制作失败')));});}
const python=path.join(run,process.platform==='win32'?'python/python.exe':'python/bin/python3');const env={...process.env,PYTHONHOME:path.join(run,'python'),PYTHONNOUSERSITE:'1',PYTHONDONTWRITEBYTECODE:'1'};
if(stage==='whiteboard-prepare'){
 let speech=[];
 if(input.config.voice){await writeFile(path.join(job,'speech-input.json'),JSON.stringify(p.scenes.map(s=>s.narration)));await writeFile(path.join(job,'speech-settings.json'),JSON.stringify({...selectedVoice(input.config),profile:voiceProfile(input.config)}));await child(python,[path.join(run,'speech/speech.py'),job],{env});speech=JSON.parse(await readFile(path.join(job,'speech-result.json'),'utf8'));if(speech.some(s=>s.profile!==voiceProfile(input.config)))throw Error('配音音色版本无效');}
 for(let i=0;i<p.scenes.length;i++){const s=p.scenes[i];s.captions=eventCaptions(s);delete s.audio;delete s.audioVoice;const name=String(i+1).padStart(2,'0');if(input.config.voice){const duration=speech[i].seconds,speed=Math.max(1,duration/29.4);if(speed>1.15)throw Error('讲解过密，请精简每幕内容以保持自然语速');await ff('ffmpeg',['-y','-i',path.join(job,name+'-raw.wav'),'-af',`atempo=${speed},loudnorm=I=-18:TP=-1.5:LRA=9,adelay=120,apad`,'-t','30','-ar','44100','-ac','1',path.join(job,name+'.wav')]);s.audio=name+'.wav';s.audioVoice=voiceProfile(input.config);const spokenMs=duration/speed*1000;s.captions=s.captions.map(c=>({...c,startMs:120+Math.round(c.startMs/30000*spokenMs),endMs:120+Math.round(c.endMs/30000*spokenMs)}));}s.captions[0].startMs=0;s.captions.at(-1).endMs=30000;report((i+1)/p.scenes.length,`正在生成配音与SRT ${i+1}/${p.scenes.length}`);}
 p.srt=toSrt(p);await writeFile(path.join(job,'course.srt'),p.srt);const parsed=JSON.parse(await child(python,[path.join(run,'skill/scripts/parse_srt.py'),path.join(job,'course.srt'),'--target-sec','30','--min-sec','25','--max-sec','30'],{env}));if(parsed.scenes.length!==p.scenes.length||parsed.scenes.some(s=>s.sceneDurationMs!==30000))throw Error('SRT分镜时长校验失败');await writeFile(path.join(job,'parsed-srt.json'),JSON.stringify(parsed));await writeFile(path.join(job,'result.json'),JSON.stringify(p));
}else if(stage==='whiteboard-render'){
 if(p.scenes.some(s=>!s.image||!s.annotation))throw Error('沙画源图或标注未完成');await child(python,[path.join(run,'render.py'),job],{env});const rendered=JSON.parse(await readFile(path.join(job,'rendered.json'),'utf8'));const ffDir=path.join(here,'node_modules/@remotion/compositor-'+process.platform+'-'+process.arch);await child(python,[path.join(run,'skill/scripts/merge_scenes.py'),'--inputs',...rendered.inputs,'--output',path.join(job,'merged.mp4')],{cwd:ffDir,env:{...env,DYLD_LIBRARY_PATH:process.platform==='darwin'?ffDir:env.DYLD_LIBRARY_PATH,PATH:ffDir+path.delimiter+(env.PATH??'')}});
 if(input.config.voice){const rows=p.scenes.map((s,i)=>`file '${path.join(job,String(i+1).padStart(2,'0')+'.wav').replaceAll("'","'\\''")}'`).join('\n');await writeFile(path.join(job,'audio.txt'),rows);await ff('ffmpeg',['-y','-i',path.join(job,'merged.mp4'),'-f','concat','-safe','0','-i',path.join(job,'audio.txt'),'-map','0:v:0','-map','1:a:0','-c:v','copy','-c:a','aac','-b:a','128k','-t',String(p.duration),path.join(job,'tutorial.mp4')]);}else await copyFile(path.join(job,'merged.mp4'),path.join(job,'tutorial.mp4'));
 const meta=JSON.parse((await ff('ffprobe',['-v','error','-show_entries','format=duration:stream=nb_frames,width,height','-of','json',path.join(job,'tutorial.mp4')])).stdout);if(Math.abs(Number(meta.format.duration)-p.duration)>.1||Number(meta.streams[0].nb_frames)!==p.duration*24)throw Error('沙画成片时长校验失败');report(1,'白板沙画已完成');await writeFile(path.join(job,'result.json'),JSON.stringify({video:'tutorial.mp4'}));
}else throw Error('未知白板沙画任务');
