import type {AnimationTheme} from './styles';
import {interpolate,useCurrentFrame,useVideoConfig} from 'remotion';
import type {Visual} from './model';
export default function Diagram({visual,color,dark,theme}:{visual:Visual;color:string;dark:boolean;theme?:AnimationTheme}){
 const f=useCurrentFrame(),{fps}=useVideoConfig(),t=f/fps,ink=theme?.ink??(dark?'#edf4eb':'#253c39'),muted=theme?.muted??(dark?'#a4b9ad':'#748a84'),surface=theme?.surface??(dark?'#263f38':'#fff'),radius=theme?.radius??20,stroke=theme?.stroke??3;
 const reveal=(i:number)=>interpolate(f,[i*fps*.4,(i*.4+.7)*fps],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'}),labels=visual.labels;
 const node=(label:string,i:number,x:number,y:number,w=190)=><g key={i} opacity={reveal(i)}><rect x={x-w/2} y={y-39} width={w} height={78} rx={radius} fill={theme?.id==='minimal'?'none':theme?.id==='paper'?(i%2?theme.secondary:color):surface} stroke={color} strokeWidth={stroke} strokeDasharray={theme?.id==='chalk'?'5 2':undefined}/><text x={x} y={y+8} textAnchor="middle" fill={theme?.id==='paper'?'#ffffff':ink} fontSize={Math.min(26,(w-24)/label.length)} fontWeight={650}>{label}</text></g>;
 const arrow=(x:number,y:number,x2:number,y2:number,i:number)=><g key={'a'+i} opacity={reveal(i)}><path d={`M ${x} ${y} L ${x2} ${y2}`} stroke={color} strokeWidth={4} strokeDasharray="8 6" strokeDashoffset={-t*22} fill="none" markerEnd="url(#arrow)"/></g>;
 return <svg viewBox="0 0 720 425" width="100%" height="100%" style={{overflow:'visible',fontFamily:theme?.font??'PingFang SC, Microsoft YaHei, sans-serif',filter:theme?.id==='neon'?`drop-shadow(0 0 5px ${color}55)`:theme?.id==='paper'?'drop-shadow(4px 5px 0 #d5cabc55)':undefined}}><defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0 0 L6 3 L0 6" fill="none" stroke={color} strokeWidth="1.5"/></marker></defs>
 {visual.kind==='fraction'?<><text x={360} y={65} textAnchor="middle" fill={ink} fontSize={50} fontWeight={700}>{visual.values[0]} / {visual.values[1]}</text>{Array.from({length:visual.values[1]},(_,i)=><g key={i} opacity={reveal(i)}><rect x={38+i*(644/visual.values[1])} y={120} width={644/visual.values[1]-6} height={155} rx={Math.min(radius,16)} fill={i<visual.values[0]?color:(theme?.secondary??(dark?'#314e43':'#e5eeea'))} stroke={color} strokeWidth={2}/></g>)}<text x={360} y={330} fill={ink} textAnchor="middle" fontSize={26}>{labels[0]}</text><text x={360} y={377} fill={muted} textAnchor="middle" fontSize={22}>{labels[1]}</text></>:
 visual.kind==='chart'?<>{labels.map((label,i)=>{const h=(visual.values[i]??(i+1)*15)/100*250*reveal(i);return <g key={i}><rect x={40+i*(640/labels.length)} y={320-h} width={640/labels.length-24} height={h} fill={color} rx={Math.min(radius,16)}/><text x={40+i*(640/labels.length)+(640/labels.length-24)/2} y={295-h} fill={ink} fontSize={26} textAnchor="middle">{visual.values[i]??(i+1)*15}</text><text x={40+i*(640/labels.length)+(640/labels.length-24)/2} y={366} fill={ink} fontSize={22} textAnchor="middle">{label}</text></g>;})}<line x1={28} y1={321} x2={692} y2={321} stroke={muted} strokeWidth={2}/></>:
 visual.kind==='orbit'||visual.kind==='cycle'?<><circle cx={360} cy={205} r={143} fill="none" stroke={color} strokeWidth={2} strokeDasharray="5 8"/>{labels.map((label,i)=>{const a=(i/labels.length)*Math.PI*2-Math.PI/2,x=360+Math.cos(a)*240,y=205+Math.sin(a)*155;return node(label,i,x,y,Math.min(190,680/Math.max(3,labels.length)));})}<circle cx={360+Math.cos(t*.8)*143} cy={205+Math.sin(t*.8)*143} r={13} fill={color}/><circle cx={360} cy={205} r={58} fill={color} opacity={.13}/><circle cx={360} cy={205} r={27} fill={color}/><path d="M340 205 L356 221 L383 190" fill="none" stroke={dark?'#123329':'white'} strokeWidth={6}/></>:
 visual.kind==='code'?<>{labels.map((label,i)=><g key={i} opacity={reveal(i)}><rect x={20} y={12+i*64} width={680} height={54} rx={Math.min(radius,16)} fill={Math.floor(t/2)%labels.length===i?color:surface}/><text x={48} y={49+i*64} fontSize={label.length>23?19:25} fill={Math.floor(t/2)%labels.length===i?'white':ink} fontFamily={theme?.font??'monospace'}>{i+1}  {label}</text></g>)}</>:
 visual.kind==='compare'?<>{labels.map((label,i)=>node(label,i,labels.length<=2?180+i*360:180+(i%2)*360,90+Math.floor(i/2)*125,280))}<line x1={360} y1={30} x2={360} y2={390} stroke={muted} strokeWidth={2} strokeDasharray="6 8"/></>:
 <>{labels.map((label,i)=>{const x=labels.length<=3?120+i*(480/Math.max(1,labels.length-1)):120+(i%3)*240,y=labels.length<=3?205:125+Math.floor(i/3)*190;return <g key={i}>{i%3!==0&&arrow(x-130,y,x-102,y,i)}{node(label,i,x,y,192)}<circle cx={x} cy={y+90} r={8+Math.sin(t*2-i)*3} fill={color} opacity={.5}/></g>;})}</>}
 </svg>;
}
