export type AnimationTheme={id:string;name:string;description:string;background:string;ink:string;muted:string;accent:string;secondary:string;surface:string;dark:boolean;layout:'split'|'stage'|'editorial';pattern:'dots'|'grid'|'paper'|'glow'|'none';radius:number;stroke:number;motion:'rise'|'draw'|'pop'|'scan';font:string};
const sans='PingFang SC, Microsoft YaHei, sans-serif';
export const animationThemes:AnimationTheme[]=[
 {id:'clean',name:'清晰图解',description:'浅白背景，深绿文字与青绿重点，圆角图形，左要点右动态图解，干净清晰',background:'#f4f8f3',ink:'#243d37',muted:'#748a84',accent:'#39847b',secondary:'#80b6a0',surface:'#ffffff',dark:false,layout:'split',pattern:'dots',radius:20,stroke:3,motion:'rise',font:sans},
 {id:'chalk',name:'黑板课堂',description:'深绿黑板，米白粉笔文字与淡黄线条，手写课堂图解，细微粉笔颗粒',background:'#142e27',ink:'#f1f4e9',muted:'#a4b9ad',accent:'#e8d783',secondary:'#8acdb5',surface:'#263f38',dark:true,layout:'split',pattern:'dots',radius:6,stroke:3,motion:'draw',font:sans},
 {id:'warm',name:'温暖手绘',description:'暖奶油纸底，棕色文字与陶橙色重点，柔和手绘轮廓，轻盈纸面纹理',background:'#fbf4e7',ink:'#49392d',muted:'#998679',accent:'#d58149',secondary:'#adbb94',surface:'#fffaf1',dark:false,layout:'split',pattern:'paper',radius:26,stroke:3,motion:'draw',font:sans},
 {id:'blueprint',name:'蓝图实验',description:'深海蓝网格底，冰蓝与青色技术线稿，直角图形与精密引线，图解居中',background:'#102f50',ink:'#e8f4ff',muted:'#8baac4',accent:'#78d6ff',secondary:'#e8ba69',surface:'#143a60',dark:true,layout:'stage',pattern:'grid',radius:0,stroke:2,motion:'draw',font:sans},
 {id:'paper',name:'纸片课堂',description:'暖白底，红蓝黄剪纸色块，清晰几何图形，错位纸层与柔和投影',background:'#fff8ec',ink:'#333844',muted:'#8b887f',accent:'#da6654',secondary:'#648fa9',surface:'#ffffff',dark:false,layout:'split',pattern:'paper',radius:3,stroke:2,motion:'pop',font:sans},
 {id:'neon',name:'霓虹科普',description:'深夜紫背景，青色与玫粉发光线条，圆形能量轨道，核心图解居中',background:'#161327',ink:'#f3eaff',muted:'#b2a4cf',accent:'#79e7ed',secondary:'#df86d9',surface:'#28213e',dark:true,layout:'stage',pattern:'glow',radius:30,stroke:3,motion:'pop',font:sans},
 {id:'terminal',name:'像素课堂',description:'深墨背景，薄荷绿像素方块与金色提示，等宽技术文字，阶梯状线条',background:'#112326',ink:'#e4f4de',muted:'#91b0a2',accent:'#a3df91',secondary:'#f0c36c',surface:'#1c3534',dark:true,layout:'stage',pattern:'grid',radius:0,stroke:4,motion:'scan',font:'monospace, PingFang SC, sans-serif'},
 {id:'editorial',name:'杂志图解',description:'象牙白底，近黑衬线标题与朱红重点，粗细分明的编辑版式，大片留白',background:'#faf8f2',ink:'#262725',muted:'#8c8a80',accent:'#c64d3d',secondary:'#697e92',surface:'#ffffff',dark:false,layout:'editorial',pattern:'none',radius:0,stroke:2,motion:'rise',font:'Songti SC, Noto Serif CJK SC, serif'},
 {id:'pastel',name:'柔彩课堂',description:'浅薰衣草纸底，雾紫和柔粉色块，饱满圆角气泡，轻柔弹入的居中图解',background:'#f5f0fa',ink:'#4c4261',muted:'#9587a8',accent:'#9483bd',secondary:'#dca5ba',surface:'#fffafd',dark:false,layout:'stage',pattern:'dots',radius:38,stroke:2,motion:'pop',font:sans},
 {id:'minimal',name:'细线留白',description:'纯白底，深灰细线和克制蓝灰重点，开放无框图解，安静简洁的居中版式',background:'#ffffff',ink:'#343d47',muted:'#94a0a9',accent:'#718da4',secondary:'#b1bcc5',surface:'#ffffff',dark:false,layout:'stage',pattern:'none',radius:0,stroke:1.5,motion:'rise',font:sans},
];
export const animationTheme=(id:string)=>animationThemes.find(t=>t.id===id)??animationThemes[0];
