use std::{collections::HashMap,fs,io::{BufRead,BufReader,Read,Seek,SeekFrom},path::{Path,PathBuf},process::{Command,Stdio},sync::{Mutex,Arc,atomic::{AtomicBool,Ordering}},time::Duration};
use serde::{Deserialize};
use serde_json::Value;
use sha2::{Digest,Sha256};
use tauri::{Manager,Emitter};
use uuid::Uuid;
#[derive(Default)]
pub struct Jobs{flags:Mutex<HashMap<String,Arc<AtomicBool>>>,busy:AtomicBool}
#[derive(Deserialize)]
#[serde(rename_all="camelCase")]
struct Manifest{build_id:String,browser_executable:String}
fn workspace(app:&tauri::AppHandle)->Result<PathBuf,String>{let s=app.state::<crate::Workspace>();let slot=s.0.lock().map_err(|e|e.to_string())?;Ok(slot.as_ref().ok_or("工作空间尚未打开")?.root_path().to_path_buf())}
fn dir(root:&Path,create:bool)->Result<PathBuf,String>{let mut p=root.to_path_buf();for name in ["data","course-media"]{p.push(name);match fs::symlink_metadata(&p){Ok(m) if m.file_type().is_symlink()||!m.is_dir()=>return Err("教程素材目录无效".into()),Ok(_)=>(),Err(e) if create&&e.kind()==std::io::ErrorKind::NotFound=>fs::create_dir(&p).map_err(|e|e.to_string())?,Err(e)=>return Err(e.to_string())}}Ok(p)}
fn name(id:&str)->Result<&str,String>{let n=id.strip_prefix("workstore-course-media:").ok_or("教程素材编号无效")?;let (h,ext)=n.split_once('.').ok_or("教程素材编号无效")?;if h.len()!=64||!h.bytes().all(|b|b.is_ascii_digit()||(b'a'..=b'f').contains(&b))||!matches!(ext,"mp4"|"wav"){return Err("教程素材编号无效".into())}Ok(n)}
fn read_path(root:&Path,id:&str)->Result<PathBuf,String>{let n=name(id)?;let p=dir(root,false)?.join(n);let m=fs::symlink_metadata(&p).map_err(|e|e.to_string())?;if !m.is_file()||m.file_type().is_symlink()||m.len()>256*1024*1024{return Err("教程素材无效或超过256MB".into())}Ok(p)}
fn save_media(app:&tauri::AppHandle,root:&Path,source:&Path,ext:&str)->Result<String,String>{let b=fs::read(source).map_err(|e|e.to_string())?;if b.len()<12||b.len()>256*1024*1024||ext=="mp4"&&&b[4..8]!=b"ftyp"||ext=="wav"&&(&b[..4]!=b"RIFF"||&b[8..12]!=b"WAVE"){return Err("渲染媒体格式无效".into())}let n=format!("{:x}.{}",Sha256::digest(&b),ext);let state=app.state::<crate::Workspace>();let slot=state.0.lock().map_err(|e|e.to_string())?;if slot.as_ref().map(|s|s.root_path())!=Some(root){return Err("工作目录已切换，教程素材未写入".into())}crate::storage::atomic_write(&dir(root,true)?.join(&n),&b)?;Ok(format!("workstore-course-media:{n}"))}
fn runtime(app:&tauri::AppHandle)->Result<(PathBuf,PathBuf,PathBuf),String>{let resources=app.path().resource_dir().map_err(|e|e.to_string())?;let mut source=resources.join("course-runtime");let mut node=resources.join("html-runtime/node");#[cfg(debug_assertions)]{if !source.join("manifest.json").is_file(){source=PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("course-runtime");node=PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("html-runtime/node");}}
 if !source.join("manifest.json").is_file(){source=crate::remote_resources::source(app,"animation")?;}if !node.is_file(){node=crate::remote_resources::source(app,"node")?.join("node");}
 let m:Manifest=serde_json::from_slice(&fs::read(source.join("manifest.json")).map_err(|_|"教程渲染组件缺失，请安装完整应用")?).map_err(|e|e.to_string())?;if m.build_id.len()!=24||!m.build_id.bytes().all(|b|b.is_ascii_hexdigit())||!m.browser_executable.starts_with("chrome/")||m.browser_executable.contains(".."){return Err("教程运行组件无效".into())}
 let cache=app.path().app_cache_dir().map_err(|e|e.to_string())?.join("course-render");fs::create_dir_all(&cache).map_err(|e|e.to_string())?;let dest=cache.join(&m.build_id);if !dest.join(".ready").is_file(){let temp=cache.join(Uuid::new_v4().to_string());fs::create_dir_all(&temp).map_err(|e|e.to_string())?;tar::Archive::new(flate2::read::GzDecoder::new(fs::File::open(source.join("app.tar.gz")).map_err(|e|e.to_string())?)).unpack(&temp).map_err(|e|e.to_string())?;fs::write(temp.join(".ready"),b"ready").map_err(|e|e.to_string())?;fs::rename(temp,&dest).map_err(|e|e.to_string())?;}
 Ok((node,dest.clone(),dest.join(m.browser_executable)))
}
pub(crate) fn whiteboard_runtime(app:&tauri::AppHandle)->Result<PathBuf,String>{let resources=app.path().resource_dir().map_err(|e|e.to_string())?;let mut source=resources.join("whiteboard-runtime");#[cfg(debug_assertions)]let mut source=if source.join("manifest.json").is_file(){source}else{PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("whiteboard-runtime")};if !source.join("manifest.json").is_file(){source=crate::remote_resources::source(app,"whiteboard")?;}let m:Value=serde_json::from_slice(&fs::read(source.join("manifest.json")).map_err(|_|"白板沙画组件缺失，请安装完整应用")?).map_err(|e|e.to_string())?;let id=m["buildId"].as_str().ok_or("白板沙画组件无效")?;if id.len()!=24||!id.bytes().all(|b|b.is_ascii_hexdigit()){return Err("白板沙画组件编号无效".into())}let cache=app.path().app_cache_dir().map_err(|e|e.to_string())?.join("course-whiteboard");fs::create_dir_all(&cache).map_err(|e|e.to_string())?;let dest=cache.join(id);if !dest.join(".ready").is_file(){let temp=cache.join(Uuid::new_v4().to_string());fs::create_dir_all(&temp).map_err(|e|e.to_string())?;tar::Archive::new(flate2::read::GzDecoder::new(fs::File::open(source.join("app.tar.gz")).map_err(|e|e.to_string())?)).unpack(&temp).map_err(|e|e.to_string())?;fs::write(temp.join(".ready"),b"ready").map_err(|e|e.to_string())?;fs::rename(&temp,&dest).map_err(|e|e.to_string())?;}Ok(dest)}
fn source_image(root:&Path,id:&str)->Result<Vec<u8>,String>{let h=id.strip_prefix("workstore-image:").ok_or("沙画源图编号无效")?;if h.len()!=64||!h.bytes().all(|b|b.is_ascii_digit()||(b'a'..=b'f').contains(&b)){return Err("沙画源图编号无效".into())}let mut p=root.to_path_buf();for part in ["data","ai-images"]{p.push(part);let m=fs::symlink_metadata(&p).map_err(|e|e.to_string())?;if !m.is_dir()||m.file_type().is_symlink(){return Err("沙画源图目录无效".into())}}crate::ai_images::read_png(&p.join(format!("{h}.png")))}
struct Busy<'a>(&'a AtomicBool);impl Drop for Busy<'_>{fn drop(&mut self){self.0.store(false,Ordering::SeqCst);}}
fn work(app:&tauri::AppHandle,request_id:&str,stage:&str,tutorial:Value,config:Value)->Result<Value,String>{Uuid::parse_str(request_id).map_err(|_|"教程任务编号无效")?;if serde_json::to_vec(&tutorial).map_err(|e|e.to_string())?.len()>256_000{return Err("教程分镜过长".into())}let state=app.state::<Jobs>();if state.busy.swap(true,Ordering::SeqCst){return Err("动画渲染器正在工作，请稍后再试".into())}let _busy=Busy(&state.busy);let flag={let mut flags=state.flags.lock().map_err(|e|e.to_string())?;if flags.len()>256{flags.retain(|_,v|Arc::strong_count(v)>1);}flags.entry(request_id.into()).or_insert_with(||Arc::new(AtomicBool::new(false))).clone()};if flag.load(Ordering::SeqCst){return Err("教程任务已取消".into())}
 let root=workspace(app)?;let _=app.emit("course-animation-progress",serde_json::json!({"requestId":request_id,"progress":0,"stage":"正在准备课程组件，首次使用需要联网…"}));let(node,run,chrome)=runtime(app)?;let job=app.path().app_cache_dir().map_err(|e|e.to_string())?.join("course-jobs").join(Uuid::new_v4().to_string());fs::create_dir_all(&job).map_err(|e|e.to_string())?;
 if stage=="render"||stage=="whiteboard-render"{if let Some(scenes)=tutorial.get("scenes").and_then(Value::as_array){for(i,s)in scenes.iter().enumerate(){if stage=="whiteboard-render"{let image=s.get("image").and_then(Value::as_str).ok_or("沙画源图缺失")?;crate::storage::atomic_write(&job.join(format!("{:02}.png",i+1)),&source_image(&root,image)?)?;}if let Some(audio)=s.get("audio").and_then(Value::as_str){fs::copy(read_path(&root,audio)?,job.join(format!("{:02}.wav",i+1))).map_err(|e|e.to_string())?;}}}}
 crate::storage::atomic_write(&job.join("input.json"),&serde_json::to_vec(&serde_json::json!({"tutorial":tutorial,"config":config})).map_err(|e|e.to_string())?)?;
 let mut cmd=Command::new(node);cmd.arg(run.join("runner.mjs")).arg(stage).arg(&job).current_dir(&run).env("WORKSTORE_CHROME",chrome).env("WORKSTORE_PARENT_PID",std::process::id().to_string()).stdin(Stdio::null()).stdout(Stdio::piped()).stderr(fs::File::create(job.join("error.log")).map_err(|e|e.to_string())?);#[cfg(unix)]{use std::os::unix::process::CommandExt;cmd.process_group(0);}
 if stage.starts_with("whiteboard-"){cmd.env("WORKSTORE_WHITEBOARD",whiteboard_runtime(app)?);}else if stage=="prepare"&&config["voice"].as_bool().unwrap_or(true){crate::ai_speech::configure(app,&mut cmd)?;}
 let mut child=cmd.spawn().map_err(|e|format!("动画渲染器启动失败：{e}"))?;let out=child.stdout.take().ok_or("教程进度管道不可用")?;let emitter=app.clone();let id=request_id.to_string();let reader=std::thread::spawn(move||{for line in BufReader::new(out).lines().map_while(Result::ok){if line.len()>8192{continue}if let Ok(v)=serde_json::from_str::<Value>(&line){let _=emitter.emit("course-animation-progress",serde_json::json!({"requestId":id,"progress":v["progress"],"stage":v["stage"]}));}}});
 let status=loop{if flag.load(Ordering::SeqCst){#[cfg(unix)]unsafe{libc::kill(-(child.id() as i32),libc::SIGTERM);}let _=child.kill();let _=child.wait();let _=reader.join();return Err("教程任务已取消，已保存分镜保留".into())}if let Some(status)=child.try_wait().map_err(|e|e.to_string())?{break status}std::thread::sleep(Duration::from_millis(100));};let _=reader.join();if !status.success(){let error=fs::read_to_string(job.join("error.log")).unwrap_or_default();return Err(format!("动画制作失败：{}",error.chars().take(800).collect::<String>()))}
 let mut result:Value=serde_json::from_slice(&fs::read(job.join("result.json")).map_err(|e|e.to_string())?).map_err(|e|e.to_string())?;if flag.load(Ordering::SeqCst){return Err("教程任务已取消".into())}
 if stage=="prepare"||stage=="whiteboard-prepare"{if let Some(scenes)=result.get_mut("scenes").and_then(Value::as_array_mut){for(i,s)in scenes.iter_mut().enumerate(){if s.get("audio").is_some(){s["audio"]=Value::String(save_media(app,&root,&job.join(format!("{:02}.wav",i+1)),"wav")?);}}}}else{result=serde_json::json!({"video":save_media(app,&root,&job.join("tutorial.mp4"),"mp4")?});state.flags.lock().map_err(|e|e.to_string())?.remove(request_id);}
 // Cached jobs contain private scripts; successful jobs are disposable, synced media remains.
 let _=fs::remove_dir_all(job);Ok(result)
}
#[tauri::command]pub async fn prepare_course_animation(app:tauri::AppHandle,request_id:String,tutorial:Value,config:Value)->Result<Value,String>{tauri::async_runtime::spawn_blocking(move||work(&app,&request_id,"prepare",tutorial,config)).await.map_err(|e|e.to_string())?}
#[tauri::command]pub async fn render_course_animation(app:tauri::AppHandle,request_id:String,tutorial:Value,config:Value)->Result<Value,String>{tauri::async_runtime::spawn_blocking(move||work(&app,&request_id,"render",tutorial,config)).await.map_err(|e|e.to_string())?}
#[tauri::command]pub async fn inspect_course_whiteboard_image(app:tauri::AppHandle,id:String)->Result<Value,String>{tauri::async_runtime::spawn_blocking(move||{let root=workspace(&app)?;let bytes=source_image(&root,&id)?;let runtime=whiteboard_runtime(&app)?;let temp=tempfile::tempdir().map_err(|e|e.to_string())?;let image=temp.path().join("source.png");fs::write(&image,bytes).map_err(|e|e.to_string())?;let out=Command::new(runtime.join(if cfg!(windows){"python/python.exe"}else{"python/bin/python3"})).arg(runtime.join("analyze.py")).arg(&image).env("PYTHONHOME",runtime.join("python")).env("PYTHONNOUSERSITE","1").env("PYTHONDONTWRITEBYTECODE","1").output().map_err(|e|e.to_string())?;if !out.status.success(){return Err("手绘源图不符合16:9或四个语义分区，正在自动修正".into())}serde_json::from_slice(&out.stdout).map_err(|e|e.to_string())}).await.map_err(|e|e.to_string())?}
#[tauri::command]pub async fn prepare_course_whiteboard(app:tauri::AppHandle,request_id:String,tutorial:Value,config:Value)->Result<Value,String>{tauri::async_runtime::spawn_blocking(move||work(&app,&request_id,"whiteboard-prepare",tutorial,config)).await.map_err(|e|e.to_string())?}
#[tauri::command]pub async fn render_course_whiteboard(app:tauri::AppHandle,request_id:String,tutorial:Value,config:Value)->Result<Value,String>{tauri::async_runtime::spawn_blocking(move||work(&app,&request_id,"whiteboard-render",tutorial,config)).await.map_err(|e|e.to_string())?}
#[tauri::command]pub fn cancel_course_animation(app:tauri::AppHandle,request_id:String)->Result<(),String>{Uuid::parse_str(&request_id).map_err(|_|"教程任务编号无效")?;let state=app.state::<Jobs>();let mut flags=state.flags.lock().map_err(|e|e.to_string())?;flags.entry(request_id).or_insert_with(||Arc::new(AtomicBool::new(false))).store(true,Ordering::SeqCst);Ok(())}
#[tauri::command]pub async fn export_course_media(app:tauri::AppHandle,id:String,path:String)->Result<(),String>{tauri::async_runtime::spawn_blocking(move||{if !id.ends_with(".mp4")||!path.to_ascii_lowercase().ends_with(".mp4"){return Err("导出文件须为MP4".into())}let root=workspace(&app)?;let bytes=fs::read(read_path(&root,&id)?).map_err(|e|e.to_string())?;crate::storage::atomic_write(Path::new(&path),&bytes)}).await.map_err(|e|e.to_string())?}
pub fn serve(app:&tauri::AppHandle,request:tauri::http::Request<Vec<u8>>)->tauri::http::Response<Vec<u8>>{let response=(||->Result<_,String>{let n=request.uri().path().trim_start_matches('/');let id=format!("workstore-course-media:{n}");let root=workspace(app)?;let p=read_path(&root,&id)?;let mut file=fs::File::open(p).map_err(|e|e.to_string())?;let size=file.metadata().map_err(|e|e.to_string())?.len();let range=request.headers().get("Range").and_then(|v|v.to_str().ok());let(start,end)=range_bounds(range,size)?;let mut body=Vec::new();if request.method()!=tauri::http::Method::HEAD{file.seek(SeekFrom::Start(start)).map_err(|e|e.to_string())?;file.take(end-start+1).read_to_end(&mut body).map_err(|e|e.to_string())?;}let mut builder=tauri::http::Response::builder().status(if range.is_some(){206}else{200}).header("Content-Type",if n.ends_with(".mp4"){"video/mp4"}else{"audio/wav"}).header("Access-Control-Allow-Origin","*").header("Accept-Ranges","bytes").header("Content-Length",(end-start+1).to_string());if range.is_some(){builder=builder.header("Content-Range",format!("bytes {start}-{end}/{size}"));}builder.body(body).map_err(|e|e.to_string())})();response.unwrap_or_else(|_|tauri::http::Response::builder().status(404).body(Vec::new()).unwrap())}
fn range_bounds(range:Option<&str>,size:u64)->Result<(u64,u64),String>{if size==0{return Err("空媒体".into())}let Some(range)=range else{return Ok((0,size-1))};let (a,b)=range.strip_prefix("bytes=").ok_or("无效范围")?.split_once('-').ok_or("无效范围")?;if a.is_empty(){let n:u64=b.parse().map_err(|_|"无效范围")?;if n==0{return Err("无效范围".into())}return Ok((size.saturating_sub(n),size-1))}let start:u64=a.parse().map_err(|_|"无效范围")?;let end=if b.is_empty(){size-1}else{b.parse::<u64>().map_err(|_|"无效范围")?.min(size-1)};if start>=size||end<start{return Err("无效范围".into())}Ok((start,end))}
#[cfg(test)]mod tests{use super::*;#[test]fn media_ids_and_ranges_reject_paths(){assert!(name("workstore-course-media:../../a.mp4").is_err());assert!(name(&format!("workstore-course-media:{}.mp4","a".repeat(64))).is_ok());assert_eq!(range_bounds(Some("bytes=5-9"),20).unwrap(),(5,9));assert_eq!(range_bounds(Some("bytes=-4"),20).unwrap(),(16,19));assert!(range_bounds(Some("bytes=21-"),20).is_err());assert!(range_bounds(Some("bytes=3-1"),20).is_err());}}
